### ISSUE TITLE
Pool Cleaning Tool/Pole Holder 🏊‍♂️

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#121]
# ⚠️ This issue contains “_first world problems_” … 🙃

> Top tip to anyone wanting financial security for themself or their family: build something the “1%” _love_ and sell it to a few of them for - what they perceive to be a “bargain” price and you will _never_ be short of cash! See: https://github.com/nelsonic/nelsonic.github.io/issues/747#issuecomment-1676256845

# Context

we have a pool. Love swimming. It’s good exercise. Kids love it. #Yolo #NoRegrets etc.
We have a bunch of cleaning tools on long poles and nowhere to store them so the end up laying around:

![IMG_7172](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/4601392b-a666-466b-88d1-567005b0f778)

# Need

what we need is some sort of storage rack for these tools so that the tools are:
a) well organised and not messy
b) easily accessible to adults
c) _not_ accessible to children who are often tempted to copy the adult and play with them which could be dangerous if they fall into the pool … 🙅‍♂️
d) away from the ficus plants so that we don’t drip salt water on them and kill them!
e) easy to make from commodity materials on our laser cutter

# Todo

+ [x] gather measurements (already did this in my paper notebook):

![IMG_7173](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/eb6c4382-ee8e-4963-b220-be09c8e91f44)

+ [x] create sketch in lightburn

+ [x] laser cut the parts

+ [x] assemble

+ [x] mount to the wall

I think I can get this done in T30m.
Let’s go!!

**Comment by nelsonic** [comment]
Got a bit of time before the kids wake up. Going to try and see how far I can get with this. 🧑‍💻 ⏳

**Comment by nelsonic** [comment]
![IMG_7174](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/9ac86bfd-84fd-4cdd-9047-d450d2b9667f)
![IMG_7175](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/2516f437-bab2-4ce2-9999-b62fa3c196be)

**Comment by nelsonic** [comment]
Test with one pole works fine:
![IMG_7177](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/84661aeb-196f-4ac1-a480-46e162e83a4d)

sadly doesn’t fit the diameter of the blue pole:
![IMG_7176](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/00357860-7784-4089-b9ec-f524a167d3bf)


But that’s ok. Gonna do a quick redesign and test again in 5 mins.

**Comment by nelsonic** [comment]
Yes, those are leaves floating on the water. I haven’t cleaned it today yet. 🙃

**Comment by nelsonic** [comment]
![IMG_7179](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/025ca55b-8aaa-444a-bb68-d4eb1fa2f408)

prototype v2 ready to test.

**Comment by nelsonic** [comment]
Works:

![IMG_7180](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/5fb4d268-b968-445d-9b6e-25cb77e9f7c9)

Let’s ship this! 🚢

**Comment by nelsonic** [comment]
I've prepared the full model for laser cutting:
![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/a002aba9-7f0d-4328-b83d-86873805c303)

Sadly, the preview says it will take `T1h` to cut on the laser ...

![screen-pool-holder-preview](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/f6299e3d-3ed8-43f1-901e-ffbe721604bf)

I don't have that kind of time right now ... so going to have to come back to this when I'm back ... ⌛

**Comment by nelsonic** [comment]
Ran the laser this morning:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/a3cfd484-5f0f-4705-a619-6be986ac86b8)

**Comment by nelsonic** [comment]
Priming the pieces:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/7fe3c236-facb-49b8-9858-fd0c0e770032)

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/125cf140-39c1-448e-a73a-d4b0d0386b47)

I always paint outside cause it airs/dries better. 👨‍🎨

**Comment by nelsonic** [comment]
All holders primed: 

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/20f40376-ac00-42a6-bbcd-beddadfc5d8f)

Heading back to my desk to write some code while the paint (primer) dries. ⏳🧑‍💻

**Comment by nelsonic** [comment]
With the primer dried on all the pieces, I painted them using my eco color paints:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/5d9fc486-a414-4cea-ba6a-9ff1eabac79d)

Ended up giving each piece _two_ coats of paint to ensure they are reasonably durable:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/6a2a6153-a011-4b38-9190-70430c6e6579)

Not expecting much "wear and tear" on these holders, but want this to last a few years and it will be placed outdoors in the elements, albeit sheltered from the rain by the overhang of our roof. 🏡

**Comment by nelsonic** [comment]
Don't worry that paint job doesn't look great in these photos ...

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/bfd387a4-e8f5-40cb-ba6f-7d36fb1a360c)

I'm going to sand all of the pieces down before mounting them.
The _effect_ I'm going for is _exactly_ the "not perfect" DIY _look_. 😉

**Comment by nelsonic** [comment]
Sanded all the pieces outside:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/a5a78d9a-af5b-4091-938c-1ba940028975)

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/cb07f702-c9bf-4202-89bb-45cb34adbb26)

Even though I was outside I still wear my respirator, safety glasses, low vibration gloves, overalls and headphones to block noise:
![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/a028160e-5c1d-4a17-92b3-9d3552953531)

**Comment by nelsonic** [comment]
You can imagine how much dust it creates:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/cbe8f849-6520-46ef-97d4-e1238af125ed)

Removed the dust with compressed air:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/5560bf1b-06ef-4781-952a-bc89b83c5c9f)

**Comment by nelsonic** [comment]
Sneak preview of assembly:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/a319dfbd-abb7-4868-a96f-29a610a17854)

**Comment by nelsonic** [comment]
Varnish applied for weather durability:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/6e8a6145-086f-4cd1-9ba8-03033e8fbbac)

On the left is one without varnish and on the right is with. 

I varnished both, don't worry!

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/13a9ffad-6e81-455d-be74-4cdfa974d75f)

this is not the place for an A/B test on the durability of unvarnished pieces. This will be outdoors and I want them to last as long as possible. 🤞🏼⏳

The QR codes still all work:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/6ed184d0-5078-40d2-a00b-4a18a5b31de5)

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/7a093e91-4de4-499e-9aee-f9e084b0d886)

Now I just have to wait for the varnish to dry. Will check back later. ⏳

I've already made the mounting holes in the wall and inserted plugs for mounting. 👌

**Comment by nelsonic** [comment]
This morning the varnish was dry so, with a little help from my DIY buddy, did the mounting:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/c9956dc3-194b-455a-a026-888c0b33fb24)

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/86bf584d-0c37-4e92-88d3-990b7253133b)

In place they look like this:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/1e3c66c0-2785-4337-b6e1-5fd2bdd01e6c)

And with the pool cleaning poles placed:

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/e27bccf2-2694-461f-9e6c-9d92bcb3f4a4)

Done. ✅
