### ISSUE TITLE
Feat: Woodworking Clamps Holder

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#122]
At present I don't have a good way of storing my Clamps ...
So they end up laying around the workshop ... 🙃 

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/74150d91-e43b-446a-8e1f-bffa5a3f9eaa)

I try to put them on the magnetic strip on the wall:
![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/8fedc93f-47ed-481c-a411-93fd66dd283c)

But this ends up taking up a _lot_ of space on the magnetic strip. 📏 
and because they don't have a well-defined place,
I'm the _only_ one who bothers to replace them after use ...

The root cause of the problem is there isn't a well-defined _system_.
Perhaps we should start there. 💭 
But I feel that having a _dedicated_ clamps holder will help me _define_ the system. 🤔 

Thinking of sneaking in an easter egg to "Clamps" https://futurama.fandom.com/wiki/Francis_X._Clampazzo 
Clip reel: https://youtu.be/g2_zb6oyep8
![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/54cc0867-9ee6-46ff-9444-dce062e69772)

# Todo

+ [x] Measure all the clamps we have small to large
+ [x] Determine how much wall space we need to store all the clamps we have **+ 30% more** (we can always use more clamps...)
+ [x] Sketch design
+ [x] Cut pieces on **`Table Saw`** for speed 
+ [x] Drill countersunk pilot holes for screws
+ [x] Assemble using our tried & true 
+ [x] Drill holes in the wall for mounting
+ [x] Mount to Wall using 4 x 30kg screws

**Comment by nelsonic** [comment]
Made something basic without the laser:

![IMG_8806](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/4c6c2f58-638e-49bf-9c44-e3c815e631c4)

includes a magnetic strip so that the clamps stay on the holder better. 👌

need to round up the rest of the clamps, which are currently in use outside, to determine if these 50cm are going to be *enough*…
but for now this is a good start. ✅

**Comment by nelsonic** [comment]
Made a lower level and sides for smaller clamps:

![IMG_8817](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/c53570f7-ce9c-4769-9327-dce65a54f86c)

our two builders are already returning clamps to the right place. #GreatSuccess ✅
