### ISSUE TITLE
FreeCAD | Learn the basics

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-cad-cam-cnc#37]
The next step is to learn the basic tools of FreeCAD for a 'feel' of the software, although there is a question here as to whether a small set of 'learn the basics' tutorials or launching right into 'learning whilst working on a practical project' is better (may warrant a separate issue).

The key for us with this repo will be that this isn't ALL the basics of FreeCAD, it is just the ones ***most relevant to laser cutting*** for now.

Whereas I think that #36 can go into the `readme` _now_ (after approval), this section cannot yet be included as first I plan to review a few videos to get a good feel for freeCAD myself and _then_ go into laser cutting specifics. The list of 'basics' will then get pared down and be able to be included in the `readme`.

Any basics that are _obviously required for laser cutting_ can be added to the `readme` as we go, without having to wait for a full list to be compiled.

## Tasks
+ [ ] Find a couple of good resources on basics
+ [ ] Review these and comment with notes on this issue
+ [ ] Pare basics down to the ones that are actually _used_ for laser cutting as we require them and add to the `readme`

**Comment by iteles** [comment]
This series is _old_, as in over 2 years old and the sound quality is terrible.
https://www.youtube.com/watch?v=CG_czsNdUfs&list=PL2935W76vRNFvUGefQr3q9P9eezJZyj-u

But it seems to be a really good review of the basic functions and as such, I'm going to zip through it to better understand the functionality of FreeCAD, seeing as I'm a beginner in parametric modelling as well as FreeCAD specifically.


+ [2 Sketches and _Constraints](https://www.youtube.com/watch?v=1JFvtkKbxBI) - Useful as goes through all constraints of the time, but these may have changed since (basics will be the same)
+ [3 Extrude](https://www.youtube.com/watch?v=f3TgcjeXDfQ)
  + Shows both **linear pad** extrude and **revolve extrude** which creates an extrude _around_ a central axis as opposed to just up or donw
+ [4 Loft](https://www.youtube.com/watch?v=s_poiUheHrw) in `Part Design`
  + Requires 2 sketches on different planes and joins them into a solid object
  + At 03:50 also teaches you to create parallel planes
  + A plane is an object whereas a sketch isn't
+ [5 Sweep](https://www.youtube.com/watch?v=P-qQSuMxjtI) in `Part Design`
  + Uses one sketch as the thing you want to extrude and the second as the path along which you're going to extrude it
  + After 30 seconds into the video it actually takes you through **sketching and constraining a sketch** pretty quickly if you want a  short recap
  + At 06:25 talks you through how to **make a groove along a specified path** in the object
  + Also discusses difference between `Part` (usually used for editing 3D parts) and `Part Design` (usually used for creating 3D parts) workbenches at 04:23
+ [7 Mirror and Patterns](https://www.youtube.com/watch?v=f6e78jss6fA)
  + Seems super useful to allow you to mirror sketches (holes, cut-outs etc) symmetrically across planes
  + At [0:35](https://youtu.be/f6e78jss6fA?t=35) he talks you through **making a hole through an object** with `Pocket`
![image](https://user-images.githubusercontent.com/4185328/94995718-1a56dc00-0598-11eb-9e48-65b233f5bafa.png)
  + Talks through a number of pattern-making tools, culminating in `Multitransform` tool to make multiple patterns at once
![image](https://user-images.githubusercontent.com/4185328/94996048-2348ad00-059a-11eb-8af4-59821c8d69ae.png)
+ [8 Boolean Operators] in `Part` workbench (also in `Part Design` if needed)
  + Talks through unions (combines 2 shapes), differences (cuts out **intersection from the object** along with the second shape), intersect (leaves **only the intersection** of 2 objects)
  

Definitely need to understand the full work cycle from computer to laser cutter to understand which ones of these are useful or not (e.g. holes in 3D vs 2D).

**Comment by nelsonic** [comment]
@iteles pad (_extrude_) is relevant when making bodies (3D) out of sketches (2D).
Ultimately if you can visualise the model in your mind you don't need to do it in 3D in CAD and can just export the 2D Sketch.
Want to try and do a walkthrough of the FreeCAD Workflow from file to Laser Cut _today_? 💭

**Comment by nelsonic** [comment]
@iteles have you had a look at the available books/e-books on Amazon? Any thoughts? e.g:

https://www.amazon.co.uk/FreeCAD-Basics-Tutorial-Assemblies-Drawings-ebook/dp/B07MKKRJJ3/
![image](https://user-images.githubusercontent.com/194400/104104954-0a3f4e80-52a3-11eb-9a6d-74efdaf32c07.png)

**Comment by nelsonic** [comment]
Best basic intro I've found/followed is by Jayanam: **FreeCAD Tutorial for Beginners**: https://youtu.be/sxnij3CkkdU
[![image](https://user-images.githubusercontent.com/194400/104124320-1b8e6680-5348-11eb-9da6-d8d40cbf1bb6.png)](https://youtu.be/sxnij3CkkdU)

The only thing to note is: he doesn't do the transition from initial Sketch to Body before the Pad. 
![image](https://user-images.githubusercontent.com/194400/104124571-7e343200-5349-11eb-8691-3bc49984ce92.png)
Remember to create a Body from the Sketch and then apply the Pad to the Sketch (inside the body).

**Comment by nelsonic** [comment]
FreeCAD 0.18 Learn By Doing: https://www.amazon.co.uk/FreeCAD-Learn-Doing-Tutorial-Books/dp/8194613701
![freecad-learn-by-doing-portugal](https://user-images.githubusercontent.com/194400/104127774-e5f37880-535b-11eb-8d98-06908bd7f0af.png)

Amazon postage/delivery to PT is £5.84 so worth searching for alternative suppliers:
https://www.bookdepository.com/FreeCAD-0-18-Learn-By-Doing-Tutorial-Books/9788194613701
![image](https://user-images.githubusercontent.com/194400/104127794-fa377580-535b-11eb-9a2b-6bb2d1aa549b.png)

Would prefer it if the book covered `v0.19` but this is a starting point. 💭 
**148 pages** is quite short. 
@iteles thoughts?

**Comment by nelsonic** [comment]
This FreeCAD Modelling Tutorial does not have voiceover but is still good practice: https://youtu.be/ytBhs6F9-t0
[![image](https://user-images.githubusercontent.com/194400/104163703-c0fc1580-53ee-11eb-90e7-4c469fa9547c.png)](https://youtu.be/ytBhs6F9-t0)

**Comment by nelsonic** [comment]
FreeCAD Beginner Tutorial Part Design:
[![image](https://user-images.githubusercontent.com/194400/104489226-4a664000-55c7-11eb-9f33-20038636aa1e.png)](https://youtu.be/iy9amRGcCCA)

This is an incredibly basic tutorial designed for complete beginners.
I followed along. The pace is good, it did not skip any steps and the narration is good.
![image](https://user-images.githubusercontent.com/194400/104489172-3c182400-55c7-11eb-9da2-8e80ebe662ea.png)

**Comment by nelsonic** [comment]
How Do the Workbenches Work Together? https://youtu.be/wXfEf8D-JDk
[![image](https://user-images.githubusercontent.com/194400/104497552-70451200-55d2-11eb-9bd7-7a39aa2d9ca0.png)](https://youtu.be/wXfEf8D-JDk)

**Comment by nelsonic** [comment]
FreeCAD Sketcher For Beginners: https://youtu.be/gbNg3mzm84s
[![image](https://user-images.githubusercontent.com/194400/104763261-8206f080-575d-11eb-885c-0bc4b9fefc97.png)](https://youtu.be/gbNg3mzm84s)

If you have already done a bit of sketching in FreeCAD, most of this tutorial will be familiar. 
But if you are new to FreeCAD or need a refresher, this is a _great_ place to start. 💡 
The video covers FreeCAD Version **`0.17`** but none of the tools used have changed so it's still relevant.

I found it great for learning the different types of constraints. 
I learned how to use
+ [x] **`Constrain Tangent`**: https://wiki.freecadweb.org/Sketcher_ConstrainTangent to create tangental curves/lines.
+ [x] **`Constrain Angle`**: https://wiki.freecadweb.org/Sketcher_ConstrainAngle to define angles in shapes
+ [x] **`Construction Lines`**: https://wiki.freecadweb.org/Sketcher_ToggleConstruction to create hidden geometry.

**Comment by nelsonic** [comment]
**FreeCAD `0.19.1`** released today! https://github.com/FreeCAD/FreeCAD/releases/tag/0.19.1
![image](https://user-images.githubusercontent.com/194400/110955707-c5d33c00-8341-11eb-85e2-5c27d6b2f7ec.png)

Going to download and try it out after work today. 🎉

**Comment by nelsonic** [comment]
FreeCAD 0.19 - Basic Part Design Tutorial: https://youtu.be/c1K-jBWytSQ
[![image](https://user-images.githubusercontent.com/194400/114318137-87c56580-9b03-11eb-8f13-156c363b1b6c.png)](https://youtu.be/c1K-jBWytSQ)

**Comment by nelsonic** [comment]
FreeCAD 0.19 - Tutorial - Part Design - Create a toy brick (English):  https://youtu.be/Pse7tcafcRM
[![image](https://user-images.githubusercontent.com/194400/115202573-6f9aab00-a0ee-11eb-97b8-09ae5df47d6c.png)](https://youtu.be/Pse7tcafcRM)

**Comment by nelsonic** [comment]
Continue: https://youtu.be/Jc12_G5DFF0

**Comment by nelsonic** [comment]
Learning how to reorient a sketch: https://wiki.freecad.org/Sketcher_ReorientSketch
<img width="1362" alt="image" src="https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/56e94189-bb4f-4147-9daf-338fa06d455a">

🧑‍💻 🤞
