### ISSUE TITLE
LightBurn?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#44]
At present the software we use to create our laser designs is _literally_ in ***Chinese***. I can make it out with my _poor_ Mandarin, but it's basically _useless_ to anyone `else` and I'm not going to invest any time in creating a tutorial for it.

According to my research, LightBurn (_which wasn't **available** when we bought our laser_) is the best in 2021.

https://lightburnsoftware.com/
![image](https://user-images.githubusercontent.com/194400/140664145-a27d1b6e-8dd2-42e6-a9a9-2b8becaef423.png)

https://lightburnsoftware.com/collections/frontpage/products/lightburn-dsp
![image](https://user-images.githubusercontent.com/194400/140664524-63380503-675a-4ccd-9baf-9d2d47db683b.png)

The _releases_ are available on GitHub:
https://github.com/LightBurnSoftware/deployment/releases
![image](https://user-images.githubusercontent.com/194400/140664163-d650fbe9-d0a8-4124-abd6-7d9aa4e51675.png)

But the software itself is Closed Source. 🙄 
I would _obviously_ prefer it to be Open Source, but at the same time I _totally_ understand why it isn't.
If it were Open Source and relied on "donations" the developer would 100% starve. 
The community of people using the software might donate $20 for it but they almost certainly wouldn't pay the €105 asking price ... I actually think €105 ($120) is a _good_ deal for this kind of industrial control software if it makes life easier. And if it means the Developer can afford to do it full-time to support it into the future, it's great!

https://lightburnsoftware.com/pages/how-the-lightburn-license-works
![image](https://user-images.githubusercontent.com/194400/140664446-6770070d-600b-4c36-a340-ecaa9fab8039.png)

The forum seem friendly and informative: https://forum.lightburnsoftware.com/
![image](https://user-images.githubusercontent.com/194400/140664046-14a0b978-48c0-4c9a-8648-23f5d7117ac3.png)

Intro: https://youtu.be/BkNeVjbZncc
[![image](https://user-images.githubusercontent.com/194400/140663529-38025bf7-52ff-425d-82b9-b89a81890d68.png)](https://youtu.be/BkNeVjbZncc)

# Todo

+ [x] Check if the controller on our laser is compatible (I think it is, but need to double-check!) 🔍 
+ [x] Download and try the trial version (Windows Machine) - need to block off a **`T2h`** for this. ⏳ 
+ [x] "Print" a couple of test pieces, see: #43 🖨️ 
+ [x] Decide if it's worth paying €105.95 for it. 💭 

Really wish I had _infinite_ time to do creative things ...

**Comment by nelsonic** [comment]
![99AEED39-E2B8-4A60-8D1E-330ABBB8BC78](https://user-images.githubusercontent.com/194400/144054111-c8952596-1fb3-42ae-a217-ae81f0805fa5.jpeg)
![FDB5D16B-FF07-4D26-848F-E453F7BD6011](https://user-images.githubusercontent.com/194400/144054132-70e14dc4-a097-4e10-a017-1a1b64b9662d.jpeg)

**Comment by nelsonic** [comment]
For reference, the DSP + Interface costs **$375**:
https://www.cloudraylaser.com/products/cloudray-ruida-controller-rdc6442g-6442s?variant=12906003857459

![ruida-controller-price-375](https://user-images.githubusercontent.com/194400/144109923-e8d6eddd-4fc0-458f-9bbd-9755e4257226.PNG)

So let's not break it. 😜

**Comment by nelsonic** [comment]
Downloaded the Free Trial of **LightBurn** this evening and it worked flawelessly. 🎉 
![lightburn-start-free-trial](https://user-images.githubusercontent.com/194400/144131285-ee44113f-b78f-4390-b58f-b40fe389aa35.PNG)

Going to do a few more tests this weekend. ⏳ 
My initial impression is that the software is worth every penny of the purchase price. 😍

**Comment by nelsonic** [comment]
Been using Lightburn for the last couple of weeks and it's been a revelation! 🎉 
It's fine for basic 2D design work e.g: #43 🖥️ 
But I still need to properly learn FreeCAD #35 to do more complex (3D/Furniture) design work ... 💭 
Meanwhile my "30 day free trial" of Lightburn is running out in the new year. 
I will be buying the App and running it on both my Mac Laptop and the Windows Desktop.

**Comment by nelsonic** [comment]
10 Tips and Tricks for New Laser owners that use LightBurn: https://youtu.be/svqLw94RjYQ

**Comment by nelsonic** [comment]
£90 ... https://lightburnsoftware.com/collections/frontpage/products/lightburn-dsp
![image](https://user-images.githubusercontent.com/194400/148450481-a5613358-632a-4f79-9673-5d7c76928301.png)

Buying the license in GBP using the UK cash/company. 

![image](https://user-images.githubusercontent.com/194400/148452032-08887f37-fb38-4b54-b33b-bcf7bec4f5b6.png)

**Comment by nelsonic** [comment]
Added the license to the CAD (Windows) PCs. Working well. Closing. ✅

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/148521820-3592b28c-fca1-4220-970b-ae7645fa301b.png)

https://lightburnsoftware.com/pages/manage-your-license-activations-with-the-license-portal
![image](https://user-images.githubusercontent.com/194400/148521860-f3dafaed-43e7-420d-b9b5-8954530b4936.png)

https://lightburn.cryptlex.app/auth/login
![image](https://user-images.githubusercontent.com/194400/148521922-3623237a-eabb-4777-adc9-963eedd355bc.png)

**Comment by nelsonic** [comment]
All about Lightburn : Interview with Jason from Lightburn: https://youtu.be/Uctq4kuu77I

[![image](https://user-images.githubusercontent.com/194400/148604323-9b18a53d-e9ca-4d87-b55f-9ccefba9facd.png)](https://youtu.be/Uctq4kuu77I)

Worth watching (or listening to) in the background to get the history/context of Lightburn. 💭

**Comment by nelsonic** [comment]
I consider myself reasonably proficient in LightBurn now. 
That's more of a testament to Jason's _superb_ software engineering skills than my abilities.
The program has the ease-of-use / no-brainer interface of MS Paint and the power/precision we need.

Recent example of a project created in LightBurn: https://github.com/nelsonic/vinyl-record-carry-storage-box/issues/1#issuecomment-1120317357

**Comment by nelsonic** [comment]
@LuchoTurtle this is the thread that might be relevant to you if you're going to try and use LightBurn for your Battery Bank. 🔋 💭

**Comment by LuchoTurtle** [comment]
@nelsonic cheers! Hopefully, some of my Blender skills can be ported into Lightburn to get up to speed faster 😛

**Comment by nelsonic** [comment]
TIL: how to cut a circle down to a semi-circle, 3/4 or 1/4. it's super easy, now that I know!
https://forum.lightburnsoftware.com/t/cutting-a-circle-in-half/5968

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/211468537-a85939c3-2798-486b-9053-ad0f26d70492.png)

lame.

**Comment by nelsonic** [comment]
![lighburn-license-renewal-scam](https://user-images.githubusercontent.com/194400/212282849-2d81071c-ebab-416b-a992-7f2b79ce9a84.png)

This is lame. But they sneakily don't include the _duration_ of the license on their website!
https://lightburnsoftware.com/collections/frontpage/products/lightburn-dsp
![image](https://user-images.githubusercontent.com/194400/212283126-c6995697-6e49-4c7d-b12b-b7f8b5d71243.png)

**Comment by nelsonic** [comment]
This is lame. But they sneakily don't include the _duration_ of the license on their website!
https://lightburnsoftware.com/collections/frontpage/products/lightburn-dsp
![image](https://user-images.githubusercontent.com/194400/212283126-c6995697-6e49-4c7d-b12b-b7f8b5d71243.png)

**Comment by nelsonic** [comment]
Wanna keep using the thing that you thought was a one-time payment? Well, there's an "Upgrade Fee" ... 🤦‍♂️ 
![lighburn-license-renewal-scam](https://user-images.githubusercontent.com/194400/212285144-eb8dcc98-eef2-4f83-b5aa-605e37b1d382.png)

**Comment by iteles** [comment]
Can we only use this on one computer?

I'm wondering if we can design some stuff during nap time this week with @stephanymtr but it would have to be upstairs (portable).

**Comment by nelsonic** [comment]
@iteles just download the App and use the 30 day Free Trial on the `M1 MacBook Air` (that @Stephanymtr is using). 
Happy to pay for more licenses if needed longer-term.

**Comment by Stephanymtr** [comment]
Hi! I have downloaded LightBurn. Here are the messages showing on my screen that stops me from doing any work on the program:
<img width="1440" alt="Screenshot 2023-11-30 at 15 23 05" src="https://github.com/dwyl/workshop/assets/91985721/2b8ad649-279a-45b2-a5d4-cf299ff71cde">
<img width="1440" alt="Screenshot 2023-11-30 at 15 25 32" src="https://github.com/dwyl/workshop/assets/91985721/0aea17a6-eb5d-4c79-91a2-1b1fd7396692">

**Comment by nelsonic** [comment]
Yeah, we need to connect the Mac to the Laser and auto-detect the settings. 👩‍💻⚡️
