### ISSUE TITLE
Kerf: how "thick" is the laser beam?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#48]
Now that I've determined the Laser Power/Speed for our machine #43 ... ⚡ 
The next step is to determine how "_thick_" the laser beam is. 
This is know as the "kerf". The term "kerf" is used in a variety of settings but is generally applied to sawing.

> Kerf: The narrow **channel left behind by the saw** and (relatedly) the measure of its width. The kerf depends on several factors: the width of the saw blade; the set of the blade's teeth; the amount of wobble created during cutting; and the amount of material pulled out of the sides of the cut. ~ https://en.wikipedia.org/wiki/Saw#Terminology

This looks like a good place to start: Kerf Tool - Full Length Tutorial https://youtu.be/h9RbBJjFjbA
[![image](https://user-images.githubusercontent.com/194400/148395766-b1b7653c-e096-4843-83ae-dfed6dfa56c2.png)](https://youtu.be/h9RbBJjFjbA)

# Todo

+ [x] Watch this tutorial and share links to any others that are relevant
+ [x] Determine if we need to buy or **`make`** our own kerf measuring tool
+ [ ] Run it on the laser to determine what our kerf is
+ [ ] Get back to work! #39 

Going to pick this up this evening after work. ⏳

**Comment by nelsonic** [comment]
While that video was a good intro, it's all in Inches (imperial measure) ... 
I _really_ wish the Americans would just join us in the future! Feet and inches are such an _arbitrary_ measure!
He spent most of the time discussing his template which is available on Etsy for a fee ... 
but doesn't do a good job of explaining the theory. So I'll keep looking ....

> **Side note**: when a video is _particularly_ slow, change the playback speed to 1.5 - 2.0 ...
> Keyboard shortcut is `<` or `>` (which on the windows PC is <kbd>shift</kbd> + <kbd>,</kbd> (comma) or <kbd>shift</kbd> + <kbd>.</kbd> (full stop) 
https://support.google.com/youtube/answer/7631406?hl=en

What is Kerf ? (And how it works with your Laser printer / cutter): https://youtu.be/OGZZI_m3PQc
[![image](https://user-images.githubusercontent.com/194400/148419313-f0b8c5ad-edc1-47cf-85ce-322e8cd6587a.png)](https://youtu.be/OGZZI_m3PQc)

![image](https://user-images.githubusercontent.com/194400/148419456-9c52e3cf-cd6b-4f32-90f9-53d8d8b96277.png)

Sadly, also in ***inches*** ... but still informative. But is basically an Ad for his Etsy (_again..._)
https://www.etsy.com/listing/889136447/kerf-tool-test-fit-guides-for-laser
![image](https://user-images.githubusercontent.com/194400/148420122-cbba160d-9e32-48b6-b4e0-416ad8aaefec.png)

I would be _tempted_ to spend the $10 if it wasn't in ***inches***!!

This looks promising: The Trick With Laser Cut Box Joints: https://youtu.be/S8AJgycY7nU (despite the clickbaity title ...)
[![image](https://user-images.githubusercontent.com/194400/148399531-e80d663b-aace-4cff-a455-822aefa2dd51.png)](https://youtu.be/S8AJgycY7nU)

The LightBurn #44 forum appears to be a good place to look too:

https://forum.lightburnsoftware.com/t/kerf-setting-in-lightburn/54219
![image](https://user-images.githubusercontent.com/194400/148404634-25e29052-56a6-49cb-a1f2-c577f67b1b14.png)

https://forum.lightburnsoftware.com/t/kerf-testing-file/520
![image](https://user-images.githubusercontent.com/194400/148404548-fc086386-7ebe-4403-90ab-bf29c3aaa187.png)

Boxes.py has a "burn test": which will increment the kerf by 0.1mm for each side:
https://www.festi.info/boxes.py/BurnTest?language=en
![image](https://user-images.githubusercontent.com/194400/148412010-26cc6a50-9548-4c23-a4d7-cc0a4cebd909.png)

Direct link:
https://www.festi.info/boxes.py/BurnTest?FingerJoint_angle=90.0&FingerJoint_style=rectangular&FingerJoint_surroundingspaces=2.0&FingerJoint_edge_width=1.0&FingerJoint_finger=2.0&FingerJoint_play=0.0&FingerJoint_space=2.0&FingerJoint_width=1.0&x=100&step=0.01&pairs=2&thickness=5.0&format=dxf&tabs=0.0&debug=0&labels=0&labels=1&reference=100&burn=0.1&render=0

**Comment by nelsonic** [comment]
Boxes.py Burn Test on 10mm ply:

![4253E0D5-B92E-4CED-9D32-2E98270477FE](https://user-images.githubusercontent.com/194400/148457025-5705c1da-a407-4fbb-9e5a-d5ff6058249d.jpeg)

**Comment by nelsonic** [comment]
kerf 0.175 test:

![A96CB537-DE81-4FCE-B473-2C3D93681B16](https://user-images.githubusercontent.com/194400/148460358-af35b3af-792a-4049-9bbb-55ec081bf075.jpeg)

Fits very well. On the reverse it’s so tight it’s practically perfect: 😍

![3712010C-769B-4E4C-8979-E9CF1513808D](https://user-images.githubusercontent.com/194400/148460599-77a0a987-8e2c-4e89-8243-39799464ae51.jpeg)

I’m *very* happy with this. 🙌

**Comment by nelsonic** [comment]
Thanked the creator of the kerf test for the file on the forum: https://forum.lightburnsoftware.com/t/kerf-testing-file/520/4?u=dc3

**Comment by nelsonic** [comment]
Found this video/tutorial to be useful in my quest:

Your First Box with LightBurn (for Beginners): https://youtu.be/gDdUzNBF6eA

[![image](https://user-images.githubusercontent.com/194400/148462482-f1a064bb-c4cc-435a-b2f6-852a9f0b854f.png)](https://youtu.be/gDdUzNBF6eA)

**Comment by nelsonic** [comment]
Feel confident I can resume my efforts on the 100mm x 100mm box now. ✅  >> #39
