### ISSUE TITLE
Workshop Storage Shelf

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#51]
The workshop looks like a tornado hit it. 🌪️ 🙄 (I have a photo and will upload it once it's "fixed"!)
This is because we don't have _any_ storage shelving/system so there are tools and "stuff" is laying around. 🤦‍♂️ 

I want to design and laser-cut a shelf _system_ that we can discretely mount to the walls that will allow us _significant_ storage space. Specifically: I want to be able to laser-cut, assemble and install each section of shelf in around 20 mins from a sheet of **1200 x 600** Baltic birch (FSC certified sustainable) ply wood:
https://www.leroymerlin.pt/Produtos/Madeiras-acrilicos/Paineis-construcao/Paineis-contraplacado/WPR_REF_11034261

![image](https://user-images.githubusercontent.com/194400/148618550-ab99a642-a9fb-4b97-9971-40bb8e0adb12.png)

The sketch I've done in my paper notebook allows for a shelf 800 (width) x 500 (depth) mm to be cut out of each sheet. 

Once the design works and I've made enough of them to tidy away the tools that are currently _on_ the top half of the laser (_again, this will make sense once you see the photo; it's really mess!!_), I will scale up the production, to a _full_ sheet of **`10mm`** Ply:

https://www.leroymerlin.pt/Produtos/Madeiras-acrilicos/Paineis-construcao/Paineis-contraplacado/WPR_REF_18896535

![image](https://user-images.githubusercontent.com/194400/148618760-53e7d94e-5d8c-4846-8815-fd9ea32c7e68.png)

This will lower my/our cost for each section of the shelving system down to **`€11.75`** 
We have 21 meters of wall to cover with the shelves. Which means we'll need to cut 26 of these shelves. 
Once they are installed we will have an _incredible_ amount of storage space and will not need to have _anything_ untidy anymore.

**`€11.75`** per ~~**800 x 500mm**~~ Edit: **950 x 450mm**  shelf section might sound like a lot for a shelf if you've never built one ... 
but trust me, this is a going to be a _bargain_ in terms of material costs! 
and the fact that all the storage space will be overhead out-of-the way "found" space will be a major bonus: 
we're _creating_ storage space out of thin air!! 😉 

# Todo

+ [x] Design the shelf in LightBurn
  + [x] Based on my paper notebook design
  + [x] Should include screw holes for mounting to the wall
  + [x] Should be easy to assemble with wood glue
  + [x] Should have a carrying capacity of 150kg - obvs not going to store anything that heavy on it! just over-engineering so that if anyone is up a ladder and distractedly hangs on one of the shelves, they won't come crashing down and injure themselves.
+ [x] Cut out on the laser using materials we already have.
+ [x] Assemble the prototype
+ [x] Install it on the south wall of the garage/workshop
+ [x] Stress test it! 
+ [x] Optimise the design for "scale production". 

I expect that this will take me around **`T2h`** in LightBurn, then **`T10m`** of cutting and **`T10m`** assembly per shelf section.
Once I have the design finalised we should be able to setup a production line to "print" the pieces, assemble and install them.

**Comment by nelsonic** [comment]
It's already **23:44** and I have a few chores to do before bed time ... 🕛 
going to need to pick this up again when I'm next at my CAD desk ... maybe only Monday night now ... 🙄 ⏳

**Comment by nelsonic** [comment]
Got an hour now before I need to get ready for lunch. Let's see how far I can get! ⏳  Cue the EDM pace-making tunes! 🎶 🎧 

![image](https://user-images.githubusercontent.com/194400/148639578-4d75145d-c2e5-4768-87cc-964c657fd7a5.png)

**Comment by nelsonic** [comment]
Design ready for cutting: 

![image](https://user-images.githubusercontent.com/194400/148642551-12cc787a-2740-4d37-98dc-28107c549fcd.png)

# 🤞

**Comment by nelsonic** [comment]
Wohh! Hold on for a second there buddy! You forgot something! 🔍  (checks requirements/spec in OP desc ...)

![image](https://user-images.githubusercontent.com/194400/148643471-6533ba60-6f22-4967-958e-7f67552e1187.png)

Mounting holes with countersink. Mandatory quote and QR Code. 
![shelf-qr-code](https://user-images.githubusercontent.com/194400/148643484-db932bdb-341f-4f3a-b8e4-eac383641d7b.png)

_Now_ it's ready ... 😉

**Comment by nelsonic** [comment]
The laser cut of the piece was a fail. 😢
Basically the material density changed so the power level I had defined for cutting did not cut through. And because the workpiece moved by a couple of millimetres doing a second pass was not an option. 🤦‍♂️

Here’s what it looked like in the machine:

![8B06675C-9B52-4FB1-A458-EF29C77178C2](https://user-images.githubusercontent.com/194400/148655977-a8317b03-dc2a-4421-9848-d201c01040b1.jpeg)

but I learned several useful/valuable things:

1. LightBurn is not smart enough to ignore lines that intersect, i.e. if two rectangles share a side it will not count that side as a single pass of the laser, rather it will always do two passes. Given the millimetre shift, the second pass wasn’t in the *exact* same place so it didn’t help with cutting through the material, it just made the kerf wider.
2. I could have used more material, I left a 20mm gap on the right and top which I can easily reduce to 5mm simply by framing the workpiece carefully (10 sec more setup time).
3. Having multiple layers is not always good especially for similar cuts/engraves. The green circle I had for countersinking the fixing screws I set to 30mm/sec @ 30% (naively) thinking that would be a good setting for removing 2-3 mm of material. The hole ended up *way* too deep, but that’s not the worst of it, worse than this, because the holes were spaced **700mm apart** and the speed was 30mm/sec - you can probably guess … - engraving the two countersink holes took almost half an hour because the laser does one “line” at a time and has to travel the full distance between the two points for each pass … ⏳not making that mistake again. I will either put the countersink on the same layer as text or put each hole on its’ own layer so it gets etched independently and doesn’t have to traverse the 700mm 50 time … 🙄
4. I need a small calibration design I can run for each workpiece to confirm the power/speed settings.
5. Finally, on re-measuring the space available (above the window) in the garage/workshop, I realised that the triangular pieces were too tall, the gap is only 260mm. So the 300mm I had would have failed. 

So overall this was a good learning experience.
I know *exactly* what I need to do on the next iteration. Next time I’m back at my CAD desk I will re-do the whole design from scratch and I should be able to get the shelf width up to 950mm. I will **_tripple_ check** the measurements before sending the design to the laser cutter. But I’m confident I will *eventually* get this right. **Hardware is _Hard_**! ® 😜

**Comment by nelsonic** [comment]
Ah, also, the QR code doesn’t work if the Colors are inverted! So gotta make sure to run it as a bitmap not a traced vector. 👍🏻

**Comment by nelsonic** [comment]
Super excited to crack on with the next iteration. 🙌
But gotta spend the rest of the weekend with family. ❤️
so removing this from **in-progress** for now. ⏳

**Comment by nelsonic** [comment]
Thinking I could already make a video of this … 💭
What would that entail? 🎥

**Comment by nelsonic** [comment]
Going to re-draw this from scratch factoring in all the changes I want to make and fixing a couple of mistakes.

**Comment by nelsonic** [comment]
Construction lines created:

![image](https://user-images.githubusercontent.com/194400/148703982-64ee12c8-e3f3-4a24-ba8f-632086454e1a.png)

Going to trace them now ... ⏳

**Comment by nelsonic** [comment]
See if you can spot the error in the above drawing ... 😜  (_it's **verrrrry subtle** ..._)

![image](https://user-images.githubusercontent.com/194400/148704124-0fe7d680-2685-40a8-830a-1f22dbfda84b.png)

**Comment by nelsonic** [comment]
https://www.goodreads.com/quotes/9588786-the-price-of-anything-is-the-amount-of-life-you

**Comment by nelsonic** [comment]
Ready for the machine: 🙌 

![image](https://user-images.githubusercontent.com/194400/148705303-7a156d3d-df0d-49f3-8c9b-22db5e5e25de.png)

Preview after optimisations: 

![image](https://user-images.githubusercontent.com/194400/148705338-691e3102-bfdc-45b6-9772-5327c1cf7392.png)

Estimated machine time is 22mins. ⏳

**Comment by nelsonic** [comment]
It's 23:30 now and while the Laser is relatively quiet ... I don't want to burn the candle at both ends. 
So going to sleep now and will do the cut tomorrow during my lunch break from "work work".

**Comment by nelsonic** [comment]
Cut the v2 design, this is how close to the edge it was:

![69D61A16-F08E-4137-B080-71E0EFBCE985](https://user-images.githubusercontent.com/194400/148762219-813a5555-58ac-4fe3-aeec-e162f4520d29.jpeg)

this one turned out 95% there:

![76AE6E1C-352A-4AAF-B93C-CB3FD9AD560F](https://user-images.githubusercontent.com/194400/148762309-65adf8c2-24a1-45d8-abba-f88aed3c37f2.jpeg)

You can see here how it goes together:

![EA9AA963-8592-450E-AA84-193A8DE7F353](https://user-images.githubusercontent.com/194400/148762388-c1b2a553-1801-4ffb-b873-2856181dbbc4.jpeg)

but sadly, the sides were wrong:

![131BF8FA-02A7-4E91-B129-8B6B8D60722E](https://user-images.githubusercontent.com/194400/148762487-e1268f24-9e4b-4dc2-a99a-b6ca3934844d.jpeg)

the “teeth” need to start at 60mm not 50mm. 🙄

so the side triangles need to be re-done. Thankfully I can cut them out of scrap material.

**Comment by nelsonic** [comment]
Re-did the shelf (triangular) sides: 

![image](https://user-images.githubusercontent.com/194400/148762943-8a9b4a55-7240-41c5-a6fe-cf09f6dfeed8.png)

Preview says it will take 3:57 mins to cut:

![image](https://user-images.githubusercontent.com/194400/148763037-21631f42-ad3e-4acb-ad1d-95bed42e189b.png)

Will get it cut as soon as I'm done with work today. 🤞

**Comment by nelsonic** [comment]
This official LightBurn tutorial was highly relevant/useful: https://youtu.be/w1hG1wv8tS4

**Comment by nelsonic** [comment]
Had 5 mins after lunch so put the machine to cut the sides:

![80564E79-B8A6-49BC-8977-1F87BE8A57C4](https://user-images.githubusercontent.com/194400/148777151-aa2a97bf-d2b9-4b14-83fe-1352c4047762.jpeg)

**Comment by nelsonic** [comment]
Had 15 mins after lunch before my next meeting so I put the side panels to cut:

![D95E8A72-6CD8-411D-9E2A-ABC13EC8B7CE](https://user-images.githubusercontent.com/194400/148784411-88d789dd-050c-4fe9-94c3-dd131bc8c429.jpeg)

Assembled the shelf with some glue and Brad nails, just to hold it all together while the glue dries:

![7A74E1AB-4B54-46DC-811D-08086F6D0860](https://user-images.githubusercontent.com/194400/148784793-04400702-b9b6-47ad-9cf3-08fe9c4aaa77.jpeg)

Not great photos. But you get the idea. 👍🏻

**Comment by nelsonic** [comment]
For "**V3**" I'm going to try and see if I can avoid cutting (burning) out the _front_ edge of the shelf:

![image](https://user-images.githubusercontent.com/194400/148845382-511ca416-774f-4bd0-8123-47bd53b8da70.png)

Also increasing the speed from **`9mm/sec`** used in V2 to **`10mm/sec`** (ignore the **`11mm/sec`** label ...)

Preview suggests it's going to take **19:30** to cut it:

![image](https://user-images.githubusercontent.com/194400/148845675-0c6e6731-be7f-4da5-9f04-d7553cca277b.png)

Going to cut this _now_. 22:00 ...  ⏳ 

Hoping to assemble one more shelf tonight and then mount it to the wall tomorrow at some point after work when it's sociable to make noise drilling 2 holes into the concrete walls... 🤞

**Comment by nelsonic** [comment]
Dang ... on reviewing my on-screen design it looks like I've made a school-boy mistake!! 🤦‍♂️ (see if you can spot it ...)

**Comment by nelsonic** [comment]
Fixed it:

![image](https://user-images.githubusercontent.com/194400/148852151-5097545c-b9c7-45df-a60e-90c0f3147dba.png)

But too late to do the laser cutting now. (23:00) 
It's amazing how much slower I work when I'm tired ... 🐌 
Going to bed. Will run the machine tomorrow morning or during my lunch break.

**Comment by nelsonic** [comment]
This evening after work, I laser-cut, assembled and mounted the second shelf based on the V3 design:


![4A61C77C-3A62-4D2A-8742-602AEA34CEBC](https://user-images.githubusercontent.com/194400/149035403-2d649d1f-876b-4dec-b24f-dca37c98134e.jpeg)

it worked well. Here is a close-up of the countersunk screw:

![AF08CD00-DE55-4A9D-9AE9-3566838571BD](https://user-images.githubusercontent.com/194400/149035538-c2b751ab-1885-4e5d-aebf-9f438649b7fb.jpeg)
![017E9973-C3AD-418C-88C9-F46957643081](https://user-images.githubusercontent.com/194400/149035542-c2093605-cd49-46fd-b3fb-d5b24080ea2c.jpeg)

I laser cut a further 2 shelves and assembled/glued them but forgot to take a photo. 🤦‍♂️
will be mounting them tomorrow evening. (Need to drill the 4 holes in the wall, which I couldn’t do tonight as our son was already asleep …)

More on the morrow! 🤞

**Comment by nelsonic** [comment]
Finished installing the 3rd and 4th shelves so now have 3.7m of shelf space: 

![B8365C2F-277A-4CD5-8950-671FCB67DDA2](https://user-images.githubusercontent.com/194400/149132417-87c38509-a0d2-41c2-aa3d-5a88d1eb20a3.jpeg)

took *less* than 10 mins to drill the holes and mount the shelves. 

obviously, this doesn’t scratch the surface of space I/we need to store everything, but it’s a very good start. 🙌

going to make one more “V4” shelf for the north side of the workshop. Then I think I can close this issue cause it’s getting loooooooong … 🙄

**Comment by nelsonic** [comment]
Made a new version from scratch for storage in the Studio which has slightly narrower dimensions:

![image](https://user-images.githubusercontent.com/194400/149237228-4d64dd85-b504-4926-bd76-e4ac73758b39.png)

Preview suggests it will take **`18:37 mins`** to laser-cut. Going to run it tomorrow.

**Comment by nelsonic** [comment]
On the north wall there is space for a double-stack of V4 shelves:

![80EC7980-A33B-440C-A559-ECAC66F939F0](https://user-images.githubusercontent.com/194400/149499953-a9fec8ce-ee03-4b93-827c-05a84918b26a.jpeg)

this is all going to make a lot more sense when I take the “after” photo of the garage/workshop in its “finished” (tidy!) stage. 😉

**Comment by nelsonic** [comment]
https://github.com/dwyl/quotes/pull/64/files

**Comment by nelsonic** [comment]
This should give you an idea of the shelves:
![garage-shelves-pic](https://user-images.githubusercontent.com/194400/153304911-20607976-8c11-4d43-b2b9-ff31c703334c.jpeg)

Closing as I consider this "done".
