### ISSUE TITLE
FreeCAD Arch Workbench: Designing Buildings using BIM

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#55]
We have learned/used several CAD programs over the years and done a few designs with those tools.
Sadly, they were all ***Closed Source***. 🤦‍♂️  
For the [**Braga `@home`** SunRoom](https://github.com/dwyl/home/issues/14#issuecomment-504559126) we did the _concept_ sketch in **SketchUp**:

![image](https://user-images.githubusercontent.com/194400/59950969-5d5a7200-946f-11e9-8497-c2d532b5fb6a.png)

While this is useful for giving people an _idea_ of what we want, it's basically only a _suggestion_ from an architectural/engineering & ***build*** perspective. What we need is a _detailed_ design that we can give to a foreman and work off.

https://wiki.freecadweb.org/Arch_tutorial

[![image](https://user-images.githubusercontent.com/194400/157053884-752949fa-7544-48a2-9de2-cdb5cad287f4.png)](https://youtu.be/8mxB6-2Ec3U0)

FreeCAD - Arch Workbench - Getting a Result, Simple House: https://www.youtube.com/watch?v=8mxB6-2Ec3U

# Todo 

+ [ ] Learn how the Arch Workbench works. 
+ [ ] Attempt to design a basic rectangular building from scratch
+ [ ] Consider ordering a book on the subject:

This book looks decent but it's unclear to me if it's for the _latest_ FreeCAD: https://www.amazon.com/-/pt/dp/B08F6TF74N
![image](https://user-images.githubusercontent.com/194400/157063856-a3158783-ae37-40cf-9947-5fc1d74af33e.png)

Available from Amazon ES: https://www.amazon.es/-/pt/dp/B08F6TF74N/
![image](https://user-images.githubusercontent.com/194400/157064023-a61575cf-ad4c-4379-b01b-691ffdf5c37c.png)

I expect this will take around **`T4h`** to learn. I _wish_ I had that time in a single block but I don't so I'm going to have to chip away at this over the next couple of weeks while juggling my other work. ⏳

**Comment by nelsonic** [comment]
@LuchoTurtle this is not a code / software engineering task. 🧑‍💻 
But it's one I _desperately_ need help with. 🙏 

Not going to "offload" it on you as that would be unfair. 👎 
But I need help in the sense that I need someone at a _similar_ level of FreeCAD + Arch knowledge to help me when I get "stuck". Again, I don't ***`expect`*** to get stuck ... but I know that having a second brain + pair of eyes will be super valuable/useful. 👀 🤞

**Comment by nelsonic** [comment]
BIM with FreeCAD - Introduction: https://youtu.be/rkWOFQ2fGZQ
[![bim freecad](https://user-images.githubusercontent.com/194400/214218923-2ae6a954-3ba6-4437-b07f-954028fd196b.png)](https://youtu.be/rkWOFQ2fGZQ)

**Comment by nelsonic** [comment]
This intro from [Yorik van Havre](https://www.youtube.com/@YorikvanHavre) is a good showcase of the capabilities. 🏡 
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/194400/214223490-f294aa38-e7ef-41f9-bb3c-293cfda3b38f.png">

**Comment by nelsonic** [comment]
https://www.youtube.com/@RegisNdeTene

**Comment by nelsonic** [comment]
FreeCAD - Arch Workbench - Getting a Result, Simple House: https://youtu.be/8mxB6-2Ec3U
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/194400/214250539-3d2c28fc-f206-4548-a7b3-5431cda04c78.png">

This is proving very insightful. But sadly I'm going to have to `return` to this later as have to do my "work work" now. 🧑‍💻

**Comment by nelsonic** [comment]
https://github.com/yorikvanhavre/BIM_Workbench/blob/master/README.md

**Comment by nelsonic** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/194400/229935729-a1bced9a-403f-4b9a-8c02-469dc880fb98.png">

following: https://youtu.be/Jc12_G5DFF0

**Comment by nelsonic** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/194400/229935851-53509a4c-87b2-4afc-bf6a-1aaa77c1bcfe.png">

**Comment by nelsonic** [comment]
On restarting `FreeCAD` and selecting the `BIM` Workbench we see the following:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/194400/229939108-fa4651dd-f40f-46f7-87d9-4461a5ccf7aa.png">

**Comment by nelsonic** [comment]
Taking this opportunity to `GitHub` Sponsor the creator of the `BIM` Addon:
https://github.com/yorikvanhavre/BIM_Workbench
Which appears to be under _active_ development ... 🤞 

https://github.com/yorikvanhavre
<img width="1448" alt="sponsor-yorik" src="https://user-images.githubusercontent.com/194400/229939864-b22776c4-3780-4d57-95a4-953251090e41.png">

**Comment by nelsonic** [comment]
Going to follow the `BIM` Tutorial when I'm able to get back to my desk ...

<img width="948" alt="image" src="https://user-images.githubusercontent.com/194400/229942738-5d33ddde-f24f-43d0-b34a-9a0c54d3df31.png">

Meanwhile opened an issue for the Welcome screen: https://github.com/yorikvanhavre/BIM_Workbench/issues/108

**Comment by nelsonic** [comment]
Patreon: https://www.patreon.com/m/481997/posts

**Comment by nelsonic** [comment]
BIM Setup:

![image](https://user-images.githubusercontent.com/194400/230223266-8454984d-cc0b-4180-8d22-073c66db503a.png)

**Comment by nelsonic** [comment]
Half way through the BIM Tutorial: 

![image](https://user-images.githubusercontent.com/194400/230478602-1420410e-9165-4e8f-8d6b-c35164854c18.png)

Going OK:

![image](https://user-images.githubusercontent.com/194400/230478835-7930f304-218a-478f-b81e-c26b226d8f0e.png)

My main advice to anyone trying to follow along with this tutorial: remember to save your work often.
then if something isn't working, just quit the program and re-open and it will fix itself. 
yes, this isn't great in terms of "stability" ... but I'm soldiering on.

**Comment by nelsonic** [comment]
Finished the BIM Tutorial. ✅ 
Confident I can start modelling the Sun Room basement. 💭  
Going to save my work _regularly_ and use a "scratch" version to do mods ... 💾 
too tired to start/focus on it now. Will start first thing in the morning. ☀️
