### ISSUE TITLE
Prototype Coat Rack for Workshop

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#56]
I'm currently hanging my painting overalls and carpentry apron on the wood rack; it's lame.
Need to design and make a simple coat rack to store these and other hanging items.

# Todo

+ [x] Measure the space available -->  **`280mm`**
+ [x] Create simple design we can cut on the Laser
+ [x] Test it virtually
+ [x] Modify the design as necessary
+ [x] Laser cut the design
  + [x] Stress Test it! (see below)
+ [x] Design and make a better coat hook: #57 
+ [x] Assemble (glue) it
+ [x] Mount it to the wall

**Note**: this isn't a high-priority feature. I can easily continue to hang my overalls on the rack.
However this is a meant to be an _experiment_ so that we can test the design for the _actual_ coat rack upstairs that _is_ a priority.

**Comment by nelsonic** [comment]
Made this one quickly in LightBurn:

![image](https://user-images.githubusercontent.com/194400/159803903-2ba84f97-246e-42eb-ade0-82cb96bec750.png)

**Comment by nelsonic** [comment]
Going to set this cutting tomorrow during lunch break. ⚡ ⏳

**Comment by nelsonic** [comment]
Laser cutting in progress:
![308E533E-54C8-4445-9687-5468245D1567](https://user-images.githubusercontent.com/194400/159809069-28f0fe10-1f64-4467-8fae-66fdcd8b4e72.jpeg)

**Comment by nelsonic** [comment]
Finished cutting it last night but didn’t upload pics cause it was late …

cut out:

![577ACBDB-A106-4DF1-A358-9797AFCD5A76](https://user-images.githubusercontent.com/194400/159942016-f77e6172-c758-4bf5-a883-cc00cc43238b.jpeg)

dry assembly:

![57AACAB2-4968-4D08-BE81-7C3352D23866](https://user-images.githubusercontent.com/194400/159942372-9600d2e0-411e-4b05-ba6f-9fc0f826c9c5.jpeg)
![711AA6A4-F061-4A2F-813E-C2A687E21D78](https://user-images.githubusercontent.com/194400/159942412-f01ff67c-2742-43e8-aee0-3588c762e507.jpeg)

Stress test:
![5B2F9AFE-444C-4182-B3DB-C98AABD84102](https://user-images.githubusercontent.com/194400/159942634-817cb98f-9a88-4ed4-9882-126b0552b323.jpeg)

![5A9902A3-D74E-441C-A9DB-CC030F6EAEEA](https://user-images.githubusercontent.com/194400/159942643-839239e4-5a32-4d8e-9da6-e2724c9e977c.jpeg)

managed to break one of the hooks by applying significant pressure. (Sadly I don’t have a scientific testing rig, so cannot say how much pressure… but I’m trying to simulate someone having off it …)

Going to revise the design of the hooks to have a bit more material at the “weak” point.

**Comment by nelsonic** [comment]
Saturday morning! 🙌☀️
Time to crack on with some Laser work! ⚡️
pew-pew! 😜


![BB41E3BF-EE52-4B6C-9448-FDAD3CCF5DCA](https://user-images.githubusercontent.com/194400/160234008-4af1eb3e-30e7-4473-bf15-9f3e898ef074.jpeg)

**Comment by nelsonic** [comment]
Coat Rack Hook sidequest: https://github.com/dwyl/learn-cad-cam-cnc/issues/57

**Comment by nelsonic** [comment]
Glueing the V4 and V3 hooks in the Workshop coat rack:
![78830950-DA1D-463C-B72D-27E3C9B6A3DD](https://user-images.githubusercontent.com/194400/160238401-f530d1c0-f56b-4de1-be8d-21a2e5c71caa.jpeg)

**Comment by nelsonic** [comment]
Mounted to the wall:
![C6A7A707-A02D-4834-BE92-3DDD8D6278EC](https://user-images.githubusercontent.com/194400/160239308-65cc8218-bb7e-4798-886e-09d5594f7cf6.jpeg)

only used one screw to test. Works well.

**Comment by nelsonic** [comment]
Hung up my overall:
![D75798C1-80E8-4FAF-A656-4D8A8E6A1853](https://user-images.githubusercontent.com/194400/160239346-ae9da4e4-2ab4-4faa-add1-def3c8a8e896.jpeg)

stoked this is going to be tidy. 🎉

**Comment by nelsonic** [comment]
Mini (structural) shelf on the top of the rack works well for storing my safety glasses:

![3847E9C3-5B0B-4971-AEEB-BE5D96D59FE5](https://user-images.githubusercontent.com/194400/160239391-aeb484e3-b704-4318-b4bb-63859a9852eb.jpeg)

Time to request feedback!

**Comment by nelsonic** [comment]
@iteles any thoughts? Areas to be improved? 💭

**Comment by nelsonic** [comment]
Closing. Goto: #58
