### ISSUE TITLE
Coat Rack for Cloak Room

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#58]
Now that I've tested the Workshop Cloak Rack #56, it's time to build the _real_ one and incorporate all the learning.

# Todo

+ [ ] Take detailed measurements.
+ [ ] Create the design in Lightburn
+ [ ] Cut it on the Laser
+ [ ] Assemble the pieces
+ [ ] Mount it on the wall!

Given that I've already done the "hard" part of designing the hooks #57,
 I expect the design of Cloakroom coat rack to take around 20mins in lightburn 
and then I will leave it cutting while doing other DIY tasks.

**Comment by nelsonic** [comment]
Here's one I made earlier:
![image](https://user-images.githubusercontent.com/194400/160301253-727eb013-c492-4cb2-bd06-83f00bccbc0b.png)

**Comment by nelsonic** [comment]
QR Code: 
![image](https://user-images.githubusercontent.com/194400/160301372-c02425e7-40e1-4241-a37f-43229a30bd8f.png)

via: https://www.qr-code-generator.com/

**Comment by nelsonic** [comment]
Laser cut going well:

![FB5882ED-E3FA-40CE-9F92-1FF5311F3A68](https://user-images.githubusercontent.com/194400/160305720-03ffe6e7-639b-4b6a-b241-ec22f45d8da4.jpeg)

Easter egg QR code reads:

![84DF236B-12ED-479B-AF91-1A240B13F479](https://user-images.githubusercontent.com/194400/160305732-26a9fe33-7763-4613-8580-08d350b1354f.jpeg)

Cut complete:

![3EF20363-6E75-48DC-85F1-4084FA32AC4B](https://user-images.githubusercontent.com/194400/160305757-ff8a91d3-28e6-4ce3-96ef-5cedb749201b.jpeg)

Going to sleep now. 😴
Will do the assembly tomorrow evening after work. 🤞

**Comment by iteles** [comment]
A little typo there on `curious` but I love it!
Are the quotes on the end to stay on the rack?

If so, maybe next time we do them without the bubbles around, looks more elegant 😉

**Comment by nelsonic** [comment]
@iteles yeah, I was thinking the same regarding the quotes. It's all an iterative process.
