### ISSUE TITLE
Support Brackets for Library Bookshelves

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#59]
Sadly, the Construction Grade Plywood I used to make the South Wall Library Bookshelves https://github.com/dwyl/home/issues/190 was not very strong ... 😢 

Long story short, I need to make 4 trusses for the shelves that have most weight on them.
I will make them out of "found" materials in the workshop and I expect it to take me around `T2h`.

# Todo

+ [x] Measure the space.
+ [x] Measure the available "found" materials (off cuts from previous projects)
+ [x] Confirm we have enough material for at least 4 trusses
+ [x]  Cut and construct the first truss as a trial
+ [x] Test mount it!
+ [x] Make 3 more trusses and mount them.

**Comment by nelsonic** [comment]
This is the laser portion of this mini project:
![image](https://user-images.githubusercontent.com/194400/161341767-46bcfa63-f23a-4c37-8cf9-9bb59b832aeb.png)

**Comment by nelsonic** [comment]
Just going to run this quick experiment to see how fast/intense I need to etch a groove instead of routing it...

![image](https://user-images.githubusercontent.com/194400/161345973-c30fd58d-a5d6-47a8-b216-bcb74c2a99fb.png)

**Comment by nelsonic** [comment]
Turns out that doing a "fill" 20 mm @ 80% power is basically nuking the 15mm plywood.
So I decreased the two test fills to 100mm @ 80% and 150mm @ 80% which were both good.
The 100mm @ 80% is best as a viable alternative to using the router table to cut grooves.
But I think I will just setup the router table now and do the routing tomorrow instead of _burning_ them.
I was just trying to do it on the Laser to avoid making noise but it's not a good replacement.
(illustrative photos of test to follow ...)

**Comment by nelsonic** [comment]
First one:

![FD111343-65FF-4D5D-86D2-C1754746E3DF](https://user-images.githubusercontent.com/194400/161394936-6268a2c6-bbe7-4d42-aa14-3caa3baf5ff2.jpeg)

All 6 ready to be mounted:

![4C818315-9FDA-4E0F-809A-C07B3AC01BC0](https://user-images.githubusercontent.com/194400/161394953-c34a6d3d-ec2e-4b9b-8821-784f1677dfc5.jpeg)

will resume this when we get home tomorrow. ⏳

**Comment by nelsonic** [comment]
I’ve done the prep work to tidy up the 3 shelves that suffered from material weakness:

![B90BE82F-B410-4B3A-A9DE-56C6F28931AC](https://user-images.githubusercontent.com/194400/161449774-86a8e673-2d9a-4274-b58f-1be26828a130.jpeg)

and calibrated and setup the two machines I need to use tomorrow evening (or whenever I have 5 mins of time to make noise):

![D5F5A834-EB2E-427F-81E0-3EED117DFD86](https://user-images.githubusercontent.com/194400/161449804-89c406c9-cab3-48ae-84ce-367d5864951f.jpeg)

I need to:
1. rip a plywood board into two 55mm strips.
2. Route the 15mm @ 5mm dept groove into both strips.
3. Cut to size.
4. Precisely drill mounting holes.
5. Mount the 3 shelves using glue & screws
6. Fix to wall
7. Measure the bracket holes
8. Drill the mounting holes for the brackets (6 x 4=24)
9. Mount the brackets
10. Test!!
11.

**Comment by nelsonic** [comment]
Drilled the 24 holes and mounted the remaining 5 brackets:

![DA931C6E-F385-40C1-80AA-3BAC767D8E0F](https://user-images.githubusercontent.com/194400/161802751-125dbaa7-2f5b-4039-b6db-abd2811ce56b.jpeg)

confident that these will now hold 200kg+:

![5BF9AC2E-3C8F-4F34-B5EC-6A3573ECB796](https://user-images.githubusercontent.com/194400/161802873-689d11ff-31a4-428d-a95b-c1c12c97821f.jpeg)

Tonight after munchkin is asleep I will repopulate the shelves with the books as per the photos: https://github.com/dwyl/home/issues/190#issuecomment-1069258552

Already placed the top shelf books:

![95531DF8-1CEC-4066-BF88-172523068097](https://user-images.githubusercontent.com/194400/161803442-0410da8c-722c-484a-9cc2-273f32c00092.jpeg)

just so we can hide the stepladder 🪜 and they are out of the way.

**Note**: in the end I made and installed 6 shelf supports. They span shelves 2 -7.
But I also reinforced ***all*** the shelves with screws from behind so they are much stronger than just glue + tack nails. 
I figured that the top shelf was already pretty strong and has the least weight on it; no plant, slightly reduced width and hard back books which are, counterintuitively, lighter than the cookbooks which have glossy higher density paper…

the bottom shelf doesn’t have a support bracket because if it for any reason it were to fail, the “fall” is only 10cm. But I’m happy to create a bracket if you think it makes sense. We have the materials and it would be a 30min job including installation. 💭

@iteles please share your feedback when you can. Thanks! 🙏

**Comment by nelsonic** [comment]
Pressed the wrong button. 🤦‍♂️
reopening.
