### ISSUE TITLE
Feat: A4 Paper Tray from 5mm Plywood

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#77]
Problem: we have _lots_ of paper around the office that needs to be sorted, organised and processed. We don't have enough trays for _temporarily_ storing it all ...
We could _buy_ those trays from IKEA, Staples, etc. but where's the fun in that? 😜 
If we make our and _learn_ from the process, we could:
a. make something _cheaper_ than the mass-produced stuff
b. make a _better_ design that meets our specific needs
c. make _dozens_ or even _hundreds_ of them for ourselves and others

# Todo

+ [ ] Create a prototype A4 Paper In-tray design 
  + [ ] Should fit a flat A4 sheet of paper with 5mm spare on all sides 
  + [ ] Should use **`5mm`** birch plywood (which we know works well on our Laser cutter)
  + [ ] Should have interlocking joints for easy assembly
+ [ ] Laser Cut the V1 prototype
+ [ ] Assemble (glue) the prototype
+ [ ] UX-test it!

**Comment by nelsonic** [comment]
![a4-in-tray-prototype-v1](https://user-images.githubusercontent.com/194400/193415196-7c95b466-1aa5-4db7-8362-aa972e2a4345.png)

Prototype V1 created. 
Going to cut it now! ⚡ ⏳

**Comment by nelsonic** [comment]
The stray (non-functional) lines were bugging me too ... so I fixed them! 😥 

![a4-in-tray-prototype-v1-tidy](https://user-images.githubusercontent.com/194400/193415480-c06d2854-2f27-46f3-adf5-43d05a3aca28.png)

**Comment by nelsonic** [comment]
Attempted to laser cut the V1 prototype:

![18B53896-FB5A-426F-810D-EA38DAD5E5CF](https://user-images.githubusercontent.com/194400/193417339-56309173-b90d-46e3-9ddb-e5e32c5fadfb.jpeg)

but the cut speed 30mm/s @ 80% was too fast so it failed. 🤦‍♂️
running it again at 9mm/s @ 80% ⏳🤞🏼

**Comment by nelsonic** [comment]
Second time worked a charm:

![BC04C717-6DBC-4ABD-ACBC-132DF5781A71](https://user-images.githubusercontent.com/194400/193427101-a8bc50d9-2462-4e87-bc67-670314fd700f.jpeg)

Going to glue it up now to UX test it tomorrow morning ⏳🤞🏼

**Comment by nelsonic** [comment]
Assembled and glue-up: 

![8C276146-18EE-46E9-8488-3D1D569E0383](https://user-images.githubusercontent.com/194400/193427774-d7297d60-e7d8-4770-8d85-d8095f04847a.jpeg)

Should be ready to test tomorrow morning when I wake up. ⏳

**Comment by nelsonic** [comment]
While waiting for the tray (glue) to dry, I felt that the depth of the tray is too much 
so I modified the design from **`85mm`** to **`65mm`**; 
uses **_fewer_ materials** and achieves the **_same_ result**:

![image](https://user-images.githubusercontent.com/194400/193430154-68a63ecf-08dd-4bba-bb23-8cce802a544f.png)

> **Note**: I actually think we could go _even_ thinner if we were to "productionise" these. e.g: **`45mm`** 💭

**Comment by nelsonic** [comment]
V2 assembled and glueing:

![7696E026-ECE9-4293-93DC-24A58ABB5B7F](https://user-images.githubusercontent.com/194400/193430629-f30c6571-9305-4a66-bd24-08519b17d1e0.jpeg)

**Comment by nelsonic** [comment]
Tested V2 (**`65mm`**) with a stack of paper and it's too deep; 🤔 
like it would encourage accumulating too much paper before processing ... 💭 

![image](https://user-images.githubusercontent.com/194400/193431626-062960dc-907a-448f-9a84-8f1964b127c7.png)


So I reduced it to **`45mm`** and tiled the **`V3`** so it will cut 3 at once. 3️⃣  

![image](https://user-images.githubusercontent.com/194400/193431598-b7b9fdd2-8b90-482a-b3b6-5fbd2d6bc7d8.png)

going to run the laser now. ⚡

**Comment by nelsonic** [comment]
Gluing the first V3 tray:

![5C60EDC4-F1BE-45F6-9CA5-FC2672C9F56E](https://user-images.githubusercontent.com/194400/193449475-9c0b8eab-92b4-4a2f-a773-d9d28c52496e.jpeg)

have limited G-Clamps (Quick-Grip) so can’t glue them all at once… my treat myself to a few more on #BrackFridayBunduru this year. 💭

Meanwhile the two I made yesterday, v1 & v2, turned out well and will be put to good use:

![13BDECDE-D648-4C8B-A503-FA3F7F550A88](https://user-images.githubusercontent.com/194400/193449528-5c14a24c-eb94-4355-90b3-8c186a0f42e6.jpeg)

Quite happy with this result. Don’t think there’s anything to improve, yet. We can revise/improve when we got feedback from @iteles once the whole thing is assembled. 🤞🏼⏳

**Comment by nelsonic** [comment]
The trays installed in the Organiser: #78 🎉 

![DABE41C1-1F7A-452E-AC5B-115A71D92AA1](https://user-images.githubusercontent.com/194400/195772859-814420d7-a9f1-4514-9e5b-23281b28b267.jpeg)

Now we "just" need to add **`labels`** to the trays to make the **`GTD System` _useful_** ... ⏳

**Comment by nelsonic** [comment]
@iteles I was just busy preparing to make labels for the in-tray system: 📥 

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/e09a007d-7db3-4115-8bfe-3d1b7e1c6aa7)

It occurred to me to _consult_ with you who are the primary "stakeholder" of this ... 💭 
Do you prefer to have a _single_ in-tray for receipts for the whole year, or have 4 trays; one for each quarter? 

![image](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/b71d95b1-b554-4278-851f-e241c4101d4c)

When you reply we can move forward with cutting and gluing these fast. 👌

**Comment by iteles** [comment]
@nelsonic Carlos has just asked us to move to a monthly system, where we hand him the invoices at the end of every month because apparently it's a LOT more work for him to do 3 months at once because of how his and the government systems are set up.

So in actual fact, the most useful labelling would be:
+ Faturas Current Month
+ Faturas Previous Month
+ Faturas To archive
+ Shoshin Outstanding actions (if a fourth is to be had, not necessarily for faturas)
