### ISSUE TITLE
Studio A4 Paper + Stationery Storage Shelf

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#78]
# Context 😕 

We don't yet have a good filing/organisation/storage system for my desk(s) in the [Studio](https://github.com/dwyl/studio/issues)
and as a result there are random bits of paper and stationery on my desk(s)
it's cluttered and it _really_ frustrates me. 🤦‍♂️ 

![9D64D49F-1288-4EAD-B2AD-A88DFBFFF1A3](https://user-images.githubusercontent.com/194400/193483634-a8250df8-4e6c-449f-938e-017820fb7f44.jpeg)

My desk(s) are full of random things and it's lame.
Yes, I could be a "minimalist" and just have _less_ stuff. 👌 
But let's _realistic_ I _need_ certain bits of paper and stationery things to get my _work_ done.
I just need them to be organised so that I can de-clutter my desk. 

What I _want_ is a ***system*** that is clear to _everyone_ including my future [assistant](https://github.com/nelsonic/nelsonic.github.io/issues/861) can **_immediately_ understand**. 

# Story 📝 

As a person who has an [**_infinite_ Todo List**](https://github.com/orgs/dwyl/projects/11) and is trying do _way_ to much,
I ***need*** to be **_hyper_ organised** and never have random bits of paper on my desk(s)
So that I can stay focussed on my highest value task and not get distracted by clutter.

## _Why_ `make` instead of _buy_ my own `paper+stationery storage system`? ⚡ 

By making my own shelving system from scratch I get _exactly_ what I want.
Not some _approximation_ made to a meet a tight budget by [**`Lars`**](https://hejsweden.com/en/swedish-names-lists-statistics) in Stockholm ...
_Nothing_ "wrong" with**`IKEA`** or any other off-the-shelf furniture; we use **`IKEA`** _often_. 
But what I've found with almost _everything_ we buy from **`IKEA`** is that it's **_never_ perfect**.

 ## How to get good at using the laser cutter? _Practice_!! ⏳ ♻️ 

Every mini-project I do on the laser I get better at designing "flat pack" furniture for high-speed/low-cost manufacturing.
Yes, I'm making one-offs or at _best_ **_ultra_-low-volume** MVPs that probably only I will ever use.
But doing this from scratch / first principals is building muscle memory of the tools 
the same way I write so many tech tutorials: https://github.com/search?q=org%3Adwyl+learn

## Other advantages of a custom-made `paper+stationery storage system` 🎉 

One of the major side-benefits of having a clear system is that it will _completely_ de-clutter the desks
which will ensure we can have a **100% Clear Desk** (at the _end_ of the day) policy 
so 

# Todo ✅ 

+ [ ] ***Measure*** the available space
+ [ ] ***Decide*** how much paper storage we want to have e.g. 12 **`A4` Paper Trays** #77 
+ [ ] ***Design*** the shelving system to fit the available space
  + [ ] **Use** the **`10mm` Plywood** we have available in the workshop
+ [ ] **Laser-cut** the design 
+ [ ] **Assemble**
+ [ ] **Mount** to the wall 
+ [ ] **`Make`** the 12 **`A4` Paper Trays** #77 **`#SideQuest`**
+ [ ] **Label _EVERYTHING_** so it's immediately clear (_obvious_) to anyone entering the studio where everything is/goes!
+ [ ] ***Use*** the system to **_stay_ organized** so that we can build awesome things together!

I _estimate_ that designing and building this will take me **`T4h`** of measuring, design, laser and assembly time.
_Obviously_ if I apply a monetary value to this shelf it's worth a _lot_ more than what I would pay at **`IKEA`** for the _partial_ solution ... but as noted above, I want to get _really_ good at this so I have to put in the time. There's no short cut!

**Comment by nelsonic** [comment]
The available space under the _existing_ studio shelf is **`880mm wide`**, **`500mm tall`** and **`200mm deep`**. 📏

**Comment by nelsonic** [comment]
The _reason_ I'm dropping my other (coding) work to do this is because the desk clutter affects me. 😖 
I _really_ need to resolve this issue once and for all so that I can get back to being an effective engineer. 👨‍💻 
Luckily I have the tools and skills to get this done. So I'm going to crack on. ⚡  
As soon as it's done I will get back to my higher _value_ coding work. ⌛

**Comment by nelsonic** [comment]
Going to make **12** paper sorting/storage trays that will be color-coded and labled. #77 📥 
Already quite happy with the progress on this. 👌

**Comment by nelsonic** [comment]
Using the built-in brave QR code generator to create my QR codes from now on:
![studio-paper-storage-shelf-qr-code](https://user-images.githubusercontent.com/194400/193487292-2deedc13-ca9a-426b-8649-2b9dd1ec7fa3.png)

I quite like the lion it includes 😉

**Comment by nelsonic** [comment]
## “_Organization is what you do `before` you do something, <br />so that when you do it, it’s not all mixed up_.” <br />~ [A.A. Milne](https://en.wikipedia.org/wiki/A._A._Milne) [ Winnie-the-Pooh ]

https://www.goodreads.com/quotes/46807-organization-is-what-you-do-before-you-do-something-so

**Comment by nelsonic** [comment]
Design prepared:

![image](https://user-images.githubusercontent.com/194400/193488449-0a60720e-bc9d-4bed-b16c-be36ac2e39aa.png)

Estimated Laser Time **`46mins`**:

![image](https://user-images.githubusercontent.com/194400/193488840-eaeaf11e-bf9a-4755-9a97-e7b0a197b0e5.png)

Boy am I glad I don't have to pay per _minute_ to use a laser cutter ... 🙄 
I 'member in London it was **`£1/min`** ... lol! 🤑

**Comment by nelsonic** [comment]
So far I'm on track to getting this done in my **`T4h`** "budget" ...

![image](https://user-images.githubusercontent.com/194400/193489155-30238835-44f5-45af-9d1b-f401cca4823a.png)

**Comment by nelsonic** [comment]
Two instances of the storage shelf installed behind the standing desk in the studio:

![DABE41C1-1F7A-452E-AC5B-115A71D92AA1](https://user-images.githubusercontent.com/194400/195772859-814420d7-a9f1-4514-9e5b-23281b28b267.jpeg)

with 13 x A4 paper trays #77 
Ready for **labels** on the trays.
I just had to put this down temporarily to focus on other work. But the final 20 minutes should be plain sailing. ⛵️

**Comment by nelsonic** [comment]
@iteles want to **`pair`** on creating the **`labels`** from **`3mm Birch Ply`** ✨ 
on the Laser some time and gluing them to the trays? ⚡ 
That way we have an at-a-glance label for each area of our lives 📥 
and can _easily_ store "to be processed" or "keep safe" paper? 🪄 

p.s. we still have space for another instance of this shelf or something else entirely that fits your needs please LMK! 🙏
