### ISSUE TITLE
Feat: @home 2nd Floor Planter Box

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#85]
This is a mini-project that has been a high priority for a _long_ time ... 
The reasons it's taken me so long to get to it are:
1. There's actually quite a lot more to this "mini" project than meets the eye. 💭 
2. The space to be filled is awkward and has several requirements 📝 
3. Each time I look at this I'm distracted by some other work ... 🙄  

I've already done quite a lot of work for this, e.g: #67 
Opening this issue to capture the rest of the work. 👌

**Comment by nelsonic** [comment]
Did a dry-fit of the box this evening, it's quite close to being done:

![image](https://user-images.githubusercontent.com/194400/202815478-22f390f0-a752-493c-a50b-871a160ef5f2.jpeg)

I estimate it's 70% complete. Just need to do the finishing, painting and installing. Sadly, won't have any time for DIY this weekend as we have family visiting. 💭

**Comment by nelsonic** [comment]
Painted the side panel:

![image](https://user-images.githubusercontent.com/194400/202823015-c1664467-cb14-4c13-887c-035a0b3445ba.jpeg)

Should be dry by the morning. ⏳

**Comment by nelsonic** [comment]
Reading: https://hortology.co.uk/pages/the-complete-guide-to-planting-houseplants-in-pots-planters#:~:text=Place%20the%20drainage%20layer%20of,compost%20which%20may%20contain%20disease.

**Comment by nelsonic** [comment]
The white paint kinda worked ... but not really ... the OSB soaked up all the paint and this is what it looked like after one [thick] coat: 

![image](https://user-images.githubusercontent.com/194400/202865036-d115ea86-c8b3-40b4-bb52-e9d6b88efab4.jpeg)

So I decided I'm not going to waste my time trying to paint OSB, but rather, I'm going to "frame" the watercolors with strips of birch plywood: 

![image](https://user-images.githubusercontent.com/194400/202865114-6ec70127-52ef-4e55-97c6-720dd9fd48b4.jpeg)

This photo isn't great, but you get the idea. 💭
It will look good in situ. 🤞🏼

**Comment by nelsonic** [comment]
Only have enough of these clamps/grips to do _half_ the glue-up:

![image](https://user-images.githubusercontent.com/194400/202865474-aecb3284-650e-447f-a7b5-3995de8d0661.jpeg)

So going to have to do this in two stages. Luckily it's quiet work so I can do the rest later tonight once everyone is asleep. 🤞🏼

**Comment by nelsonic** [comment]
Glued the rest of the picture frame borders:

![image](https://user-images.githubusercontent.com/194400/202872662-65abb45e-b0c9-4555-b63f-49e577eedc69.jpeg)

**Comment by nelsonic** [comment]
# What Next? (Production Plan)

- [ ] Drill 4 countersunk holes in picture panel
- [ ] Measure position for wall mounting hole
- [ ] Measure cut points for installing 
- [ ] Take box back down to workshop for finishing
- [ ] Cut second internal panels from plywood as it will be more waterproof
- [ ] Install internal panels
- [ ] Tape internal lines for painting
- [ ] Paint internal with waterproof paint
- [ ] paint second layer of WP pain
- [ ] Sand and finish final pass
- [ ] Varnish all visible sections
- [ ] wait patiently for paint and varnish to dry
- [ ] Carry upstairs 
- [ ] Install box
- [ ] Install picture panel
- [ ] Add soil
- [ ] Add plants 🌱

**Comment by nelsonic** [comment]
![E9DB82B3-B6B4-4EC8-B68C-102AF93123C4](https://user-images.githubusercontent.com/194400/212176222-fc176ae4-45f1-4a11-86d8-5801850319d0.jpeg)

box installed. Now to fill with gravel, soil, organic matter and plants. 🪴

**Comment by nelsonic** [comment]
@iteles this is now installed and ready to be filed with organic matter and ***Plants***!! 🎉 
Want to help _select_ the plants this evening and we can get them all planted tomorrow? 🪴 🛒
