### ISSUE TITLE
Feat: Custom Bed Side Table / Night Stand Shelf

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#89]
I don't currently have a bed-side table so my things aren't organised. 😢 
It's lame and I feel the **`pain`** of it every morning and night.
It's obviously not a _lot_ of **`pain`**, but it's persistent and thus _cumulative_. 
I want to ***fix*** this so that every day I start and end with a ***`SYSTEM`***. 

# Required:

+ [ ] Spot for charging/gripping **`iPhone 6S`** should allow screen to remain on (face down)
  + [ ] In-ear Headphones organising/holding spot
+ [ ] iPhone 13 charging
+ [ ] Kindle storage + charging
+ [ ] Apple Watch Charging stand
+ [ ] Storage for Eye mask
+ [ ] Storage shelf for **PJS**
+ [ ] Light with easily findable switch
+ [ ] Space for tiny notebook for journaling / final notes for the day.

# Todo

+ [ ] Measure available space between bed and wall
+ [ ] Measure all devices 
+ [ ] Explore non-destructive mounting to the bed frame e.g. using **Small Rig** or G-Clamp
+ [ ] Design the most compact + functional solution to this problem
  + [ ] Use both Laser and traditional woodworking techniques
+ [ ] Create _short_ ***`VIDEO`*** of the project!!!!!!!!

**Comment by nelsonic** [comment]
Thinking of integrating a magsafe wireless charger so that I can just place my phone an it will charge: 🔋 
https://www.tek4life.pt/pt/carregador-wireless-compativel-apple-magsafe-15w-branco
![image](https://user-images.githubusercontent.com/194400/205520003-06a54811-d44b-45d0-bc91-24d22a79c522.png)
