### ISSUE TITLE
Apple Box

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#9]
While watching Indy Mogul's "10 Essential Film Tools" video I learned about Apple Boxes:

[![image](https://user-images.githubusercontent.com/194400/66631667-9b39fc80-ebfe-11e9-8572-d56f1f61a131.png)](https://youtu.be/a1y7smPtpyc)
https://youtu.be/a1y7smPtpyc

![image](https://user-images.githubusercontent.com/194400/66632750-0dabdc00-ec01-11e9-82ed-949b26186f06.png)

https://www.adorama.com/mt259535.html
![image](https://user-images.githubusercontent.com/194400/66631755-d6d4c680-ebfe-11e9-9069-0e2ad88e51fe.png)

https://www.filmtools.com/grip-and-electrical/grip-essentials/appleboxes/filmtools-apple-box-full.html
![image](https://user-images.githubusercontent.com/194400/66631578-501fe980-ebfe-11e9-841b-a16864632b20.png)

$36.35 for a wooden box ... 

# Todo 

+ [ ] Get _Exact_ Dimensions in `mm` > 20" x 12" x 8" > 50.8 x 30.48 x 20.32 
https://www.google.com/search?q=20+inches+in+cm
+ [ ] Clone it in Fusion 360
+ [ ] Send design to Samir 3D Workshop
