### ISSUE TITLE
Library Rules + Quote Sign

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#95]
# Todo

+ [ ] Measure the space available for the library sign
+ [ ] Finish writing the "Library Rules"
+ [ ] Decide what quote to put at the bottom of the sign
+ [ ] Print on Laser Cutter
+ [ ] Finish with sandpaper and paint as necessary.
+ [ ] Mount!

Thinking of using this quote: 

# "_The person who does not read <br />has no advantage over <br />the person who cannot read._" 

Though often attributed to Mark Twain, this cannot be verified: https://quoteinvestigator.com/2012/12/11/cannot-read/

**Comment by nelsonic** [comment]
https://www.goodreads.com/quotes/tag/reading?page=4

# “One glance at a book and you hear the voice of another person, perhaps someone dead for 1,000 years. To read is to voyage through time.” ~ Carl Sagan

also super like this one:

## “_So Matilda’s strong young mind continued to grow, <br />nurtured by the voices of all those authors <br />who had sent their books out into the world like ships on the sea. <br />These books gave Matilda a hopeful and comforting message: <br />You are not alone._” <br />~ Roald Dahl, [Matilda](https://www.goodreads.com/work/quotes/1015554)
