### ISSUE TITLE
Garden Quote Sign for Side of Planter Box

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#97]
With the 2nd floor planter box https://github.com/dwyl/learn-cad-cam-cnc/issues/85 nearing completion,
there's **One More Thing<sup>TM</sup>** we need to add! A laser-cut sign! 

# Todo

+ [ ] Create a quote sign with the quote below:
+ [ ] Stylised Outline/Line-art drawing of Audrey Hepburn to go with the quote. 
  The only requirements are:
  + [ ] Hair up (not the short-haired version)
  + [ ] No Cigarette or makeup stick
  + [ ] Minimal or no jewellery (to keep it as simple as possible) 

# “_To plant a garden is to believe in tomorrow._” <br />~ Audrey Hepburn
ref: https://www.goodreads.com/quotes/831377-to-plant-a-garden-is-to-believe-in-tomorrow

The _difficult_ part in this is finding, _or **creating**_ the line-art so that it looks good when Laser-cut. 

There are plenty of examples of this on Google Images:
https://www.google.com/search?q=Audrey+Hepburn+outline&source=lnms&tbm=isch

![image](https://user-images.githubusercontent.com/194400/211017228-cb97945c-2f17-4005-86b3-9af5ae9a1303.png)

![image](https://user-images.githubusercontent.com/194400/211017244-02843acd-c1dc-45b2-ab0e-458e39f45fc1.png)

![image](https://user-images.githubusercontent.com/194400/211017281-f9f05502-6f0e-445d-838d-8f7a1c41e11f.png)

I _particularly_ like this last one:

![image](https://user-images.githubusercontent.com/194400/211017668-e3d946a7-1f82-4b3f-8942-b1d63a97b825.png)

If we were to use this epic polygon one, we would need to remove the cigarette ... we can probably do that in LightBurn... 💭 
Simply import the drawing, convert to path and then select the parts we want to remove. ✂️ 

@Stephanymtr can you help with sourcing a great image for this?
If you can find a ready-made one that works well on the Laser Cutter, that's great! Less time spent. 🎉 
But if you cannot find a _great_ one, then you will need to dust off your artistic skills! 👩‍🎨 
You will need to draw inspiration from various source images so copy and paste them into the comments of this issue. 🙏 
and then create your own. ⏳ 
We can do a test-cut whenever you are ready. ⚡

**Comment by Stephanymtr** [comment]
Hi @nelsonic 

What do you think about this one ? OR did you want her hair to be all at the top ?

https://www.drawingtutorials101.com/how-to-draw-audrey-hepburn-step-by-step
![image](https://user-images.githubusercontent.com/91985721/211036693-4e148087-cfd7-400f-b94f-ce5a97eefb26.png)

I used a few different online photo retouch website to save time in removing the cigarette holder from her hand, but doesn't look good (imagine below) The mouth and fingers look weird. It would have to be an actual program...Light Burn, like you said.

![imageedit_10_2582017334](https://user-images.githubusercontent.com/91985721/211044180-8e3b8c6d-b0ca-4f9f-85c0-394c6bb2b43d.gif)

**Comment by nelsonic** [comment]
@Stephanymtr thanks very much for taking a look at this 👀 
and removing the cigarette from Audrey's hand in the "Triangles" drawing. 👍 
You're right, it looks weird. 😕 
If I had infinite time, ⏳ 
I would re-draw it myself with the hand either on the chin 👨‍🎨 
or completely out of the picture as it's not needed if there's no cancer-stick. 🚭 

This one is more recognisable as Audrey as it's taken directly from a photograph: 📷 
![image](https://user-images.githubusercontent.com/194400/211137831-1a2597a7-9603-490e-8665-967419a2f7fb.png)

Going to try it on the laser and see how it looks. 💭

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/211163531-90b36ac1-cf38-4fb5-8ff4-f144ada68d61.png)
![image](https://user-images.githubusercontent.com/194400/211163565-6e77a567-f1b9-460c-ba94-44e81ddc1038.png)

Thoughts?

I've put the text on the _right_ of the silhouette ... 🗯️ 
Would it look better on the _left_... 🤷‍♂️

**Comment by nelsonic** [comment]
Sent to laser last night: ⚡️ 

![F4BF2FEA-9F9D-4F99-BB17-D54CB9443DC2](https://user-images.githubusercontent.com/194400/211496905-d20bd366-72af-4193-ac93-166a46ea28fb.png)

Now need to finish and apply it. ⏳

**Comment by nelsonic** [comment]
![E3572F85-3E2D-4358-AC0A-0774EA7F31F5](https://user-images.githubusercontent.com/194400/212175759-27f42343-92ba-4eaf-a71d-fc1a1aaa032d.jpeg)

obvs this would have looked a *lot* better if I had laser etched the quote directly into the plywood i made the planter box out of. But after a couple of tests I wasn’t confident that it wouldn’t made a mess of the much higher density plywood so I decided to play it safe and apply the quote sign retrospectively.

**Comment by iteles** [comment]
Looks so good!

**Comment by nelsonic** [comment]
Hopefully people read it and are inspired to plant more gardens. 🌱 🪴 🌳 🥑 😋
