### ISSUE TITLE
Feat: Attic Storage Shelves

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#99]
As agreed in: https://github.com/dwyl/home/issues/220 building the **`Attic Storage Shelves`**
are a "***keystone***" to de-cluttering/tidying/organising the house. 🏡 
So that's what I'm focussing on for the next couple of days. ⏳ 
I'm going to follow a **_similar_ design** to the **Library Bookshelves**: https://github.com/dwyl/home/issues/179#issuecomment-1376723158 📚 
Going to use **`15mm` Birch Plywood** (_same as the library_) 🪵 
even though I could _probably_ get away with using **`10mm`** ... 💭 

# Todo

+ [ ] ***Measure*** the available space on the **`main` wall** of the **`Attic`**
+ [ ] ***Calculate**** how many **`IKEA SAMLA` Transparent Storage Boxes** we can fit along the length.

https://www.ikea.com/pt/en/p/samla-box-with-lid-transparent-s69440761/
![image](https://user-images.githubusercontent.com/194400/212571835-2a2d653d-e62d-4ebf-82cc-8021a6b3df9a.png)
![image](https://user-images.githubusercontent.com/194400/212571896-41f9fa7c-f6ab-42ac-a702-4f324aee337e.png)

+ [ ] ***Calculate*** how many **vertical supports** we need based on how many **`SAMLA` Boxes** fit.
+ [ ] ***Measure*** length of the cabin of the **`TOYOTA PROACE 1.6 D4D (MDX9) 90`** (delivery van) https://github.com/dwyl/learn-cad-cam-cnc/issues/98
+ [ ] **Prepare Cutting List** on [`2440x1200-ply-template.svg`](https://github.com/dwyl/home/blob/main/utility-room/2440x1200-ply-template.svg)
  > Note: the constraint to respect is the _internal_ dimensions of the van.
+ [ ] ***Print*** cutting list to take to **`Leroy Merlin`** factoring in the Transport Van Constraint.

**Comment by nelsonic** [comment]
Gonna need 3 whole sheets of Plywood for this ...

![attic-horizontal-cutting-list-2](https://user-images.githubusercontent.com/194400/212712905-dbf2144d-ae12-413d-bc33-6aafbe7eda9f.svg)


![attic-horizontal-cutting-list](https://user-images.githubusercontent.com/194400/212712797-55fbd3e0-54f7-42e9-8527-01feb7bb32c0.svg)

![attic-shelf-vertical-cutting-list](https://user-images.githubusercontent.com/194400/212712947-497895b0-d3a8-435a-a9c7-204b806ff11d.svg)

Printed and ready to head to Leroy Merlin now. ⌛

**Comment by nelsonic** [comment]
FYI: this is my sketch:

![AF9E9049-20FE-4FEA-B0C4-EDBE66F788CE](https://user-images.githubusercontent.com/194400/212713271-1b63e42f-869f-430c-86d8-4ef3a231e8e2.jpeg)

I calculate that we will fit 29 of the IKEA SAMLA storage boxes in the space I’m going to create. That’s _lot_ of storage … 💭

**Comment by nelsonic** [comment]
This is the area of wall I’m covering with shelves:

![34AD9598-39A8-4FC2-8440-8FF38137F503](https://user-images.githubusercontent.com/194400/212943187-4aa743cb-b3b6-443e-a1d2-65c1d71476f9.jpeg)

as you can see, the floor is a bit rough:

![F8695379-27CA-428E-93FA-6F2602B660A5](https://user-images.githubusercontent.com/194400/212943257-13fbcf1f-e50d-4520-922c-ee9066716a6e.jpeg)

It’s not that bad, but it could be a tripping hazard which we definitely want to avoid for people carrying a box and not looking where they are walking … 💭

so I’ve asked Miguel to flatten the chunky bits and then smooth the surface with some fine cement. Going to put the Dehumidifier in there to help it cure/dry. Once that is done I will install the shelves that I’m working on in the workshop _now_. ⏳

**Comment by nelsonic** [comment]
Decided to cut the grooves _manually_ with my pull saw:

![EDD9B6EE-DED0-48FE-A52E-83A5537B5D0D](https://user-images.githubusercontent.com/194400/212955348-4cb0fd6a-9678-4190-a90c-b58285b9ac1c.jpeg)

way more accurate than the electric one. 👌

**Comment by nelsonic** [comment]
Happy with this fit:

![575D2729-87D5-49E0-8373-9FA12C6E4374](https://user-images.githubusercontent.com/194400/212957996-057f457f-02be-460a-926d-f8e390bb4ee6.jpeg)

on to the next one. ☝️

**Comment by nelsonic** [comment]
The cement fixing the level of the floor in the attic is almost dry:

![8DCEE858-CB02-4D69-8BDA-567BAAED9052](https://user-images.githubusercontent.com/194400/213197362-68a46fdb-314f-4d9b-8648-9ee528132658.jpeg)

I’m done with cutting the pieces of shelf system and am now doing a dry assembly:

![A3D4BC23-D6F2-4728-BA80-546255D4501A](https://user-images.githubusercontent.com/194400/213197613-feb8dbc2-09b1-4710-a748-bf16526e6d3e.jpeg)

**Comment by nelsonic** [comment]
Minor setback:

![415841DC-228F-4732-AF91-015CD019BB94](https://user-images.githubusercontent.com/194400/213199043-7c572d62-ce84-46f0-93c4-2408bad6916f.jpeg)

while dry installing the vertical support (with a mallet) the plywood split! 😢

**Comment by nelsonic** [comment]
Getting it up the the first 4 flights of stairs from the workshop to the 2nd floor was easy:

![Uploading 775A7FED-3B48-4FEB-A9BF-A3DBFC50859E.jpeg…]()

**Comment by nelsonic** [comment]
But getting it up the Attic spiral staircase was a bit more of a challenge:

![4AE80760-C0CA-4A31-926B-C2032D82A2F9](https://user-images.githubusercontent.com/194400/213222064-d48aab43-2aec-4b9f-9dd6-24f7b8cc175c.jpeg)

**Comment by nelsonic** [comment]
But with some Tetris skills, we made it up here:

![8D93ED00-E9EB-45CF-ABCE-525CA009FFD5](https://user-images.githubusercontent.com/194400/213222312-2a16ad5d-50c9-4393-b353-f1dcdc561819.jpeg)

here are two of the storage boxes for context:

![89C0B688-0D11-47F0-BD24-3AB8F1E25B51](https://user-images.githubusercontent.com/194400/213222515-f55a51ba-e618-4e3b-bc81-799a6176f0d1.jpeg)

**Comment by nelsonic** [comment]
Confident that the _bigger_ shelving unit will *definitely* not fit up the attic spiral staircase. We will *100%* need to assemble it in situ.

going to work on measuring everything tonight and preparing the cuts to be done tomorrow. 🤞🏼

**Comment by iteles** [comment]
Are any more 'works' going to be done up in he attic that will create dust etc or can I start packing on the boxes?

**Comment by nelsonic** [comment]
I'm going to drill 2 strategic holes into the brick walls to fix this shelf system to the wall so that it cannot fall forward.
But I will use dust collection while drilling so don't expect to make too much dust, but will promptly clean it.
These shelves are ready to receive the first 12 boxes _now_.

**Comment by nelsonic** [comment]
Really want to build the _second_ set of shelves that will have space for **17 boxes** 📦 
so that I can consider this mini-project _done_. 🤞 
But need at least 3h of workshop time 🕒 
and not expecting to get that tomorrow 🙄 
as have _lots_ of work-work https://github.com/dwyl/product-roadmap/issues/43 to do ... ⏳

**Comment by nelsonic** [comment]
Added fixing bracket to wall:
![9113288A-CE77-4875-8F4B-68CABDDA6B23](https://user-images.githubusercontent.com/194400/213701641-8a42bb49-6e03-467d-8845-24e0c2005659.jpeg)

and on the west side (of the building) it’s wedged in tight:

![7E98F393-4D84-453E-B0F0-1BD324DD8FE4](https://user-images.githubusercontent.com/194400/213701731-d0e71a63-8282-4e47-85b8-c1ab724a2a22.jpeg)

this section of the shelving system is now considered operational.🚀

**Comment by nelsonic** [comment]
Going to do a bit of prep work on the second set now. 🪚
@iteles you should already be able to stack 12 boxes on these shelves without any issues. 👌

**Comment by nelsonic** [comment]
Visible Rubber mallet 🔨 marks from assembly:

![2E86BE9E-5B76-4B45-92E7-14ECE49E9C9B](https://user-images.githubusercontent.com/194400/213702431-5b66a78e-bd23-4c35-a857-b8aadcd0c9fa.jpeg)

Screws keep the shelves in place *permanently* but are not visible once the second set of shelves are installed.

This is my [bricolage](https://youtu.be/V1GHxA7XCo0).

**Comment by nelsonic** [comment]
All 9 pieces of the second shelving unit ready for fitting:

![D2300C07-9D9A-410C-95E5-0266FFE2ED62](https://user-images.githubusercontent.com/194400/214338869-a5113239-ab1c-4b4f-b889-13b854e5ab04.jpeg)

**Comment by nelsonic** [comment]
sadly, “Thor” got the best of the rubber mallet:

![3229ABBE-7F1D-40B2-8267-21D0AE4B5777](https://user-images.githubusercontent.com/194400/214340421-1047dbcd-cd69-435c-8889-69b2e39d2a5d.jpeg)

it’s not “fixable” … 😢
![27A62AB5-35BF-4571-8FB1-5E2A3D3BE9F3](https://user-images.githubusercontent.com/194400/214340876-d03f6121-98f3-4a7d-a8e3-74f6e935f8be.jpeg)

poor Draper mallet; it’s had a good run. (I’ve had it for 7 years and it’s done time on most of my woodwork projects … ⏳

going to upgrade to something better. 💭
Meanwhile, sadly, cannot continue with the Attic Storage System installation. 😢 ⏯️

**Comment by nelsonic** [comment]
Going to try my luck with my Dexter Masonry Hammer:
![6F77C7B3-9C38-4E58-93F2-EBBA3D837313](https://user-images.githubusercontent.com/194400/214342910-8916e14f-ac43-4c03-b0cb-c6e7fd683aaf.jpeg)

Have a piece of scrap plywood to protect the shelf while using the hammer. 
will reverse the workpiece so that I’m hammering from behind and lay down a towel to protect the front of the shelf.

**Comment by nelsonic** [comment]
for the second half of this unit, I’m going to use wax (parafin) to lubricate the joint, reducing friction:


![33125516-564C-4B95-9A4E-B6B61728F480](https://user-images.githubusercontent.com/194400/214612553-7520381a-ddf6-47c8-ae8c-fa7cc66807f0.jpeg)

The combination of heavier masonry hammer and wax meant the installation of the remaining 2 shelves went *muuuuch* smoother/quicker:

![B58910AB-82E5-4611-A9ED-7CC18DBCF7EB](https://user-images.githubusercontent.com/194400/214612603-1b0d4df0-5463-43ab-831e-cbe8dd9ec0da.jpeg)

note-to-self: always use wax when fitting tight lap joints!! 💭

**Comment by nelsonic** [comment]
Second shelving unit/system is installed. 

![5393148B-58D3-4A0D-AA63-43E7B95F51F7](https://user-images.githubusercontent.com/194400/214613953-4cdbd73a-91c3-4022-a7f2-b283182a85a2.jpeg)


Now just need to drill a hole in the wall to fix it in place and can call it done!

**Comment by nelsonic** [comment]
@iteles you have space for 31 boxes. 📦 
Is that “enough” for now? Or should I get to work on filling the other walls with shelves already? (Can I get back to me desk work now..?) 🧑‍💻

**Comment by nelsonic** [comment]
Fixing screws in the wall and shelf:

![B98FB93C-57B9-486A-8013-56F603D086B1](https://user-images.githubusercontent.com/194400/214618607-596f3a21-42e8-48a3-a2ae-dd7c5ffcabd7.jpeg)

this will prevent any wobble from the uneven floor. 👌
Done ✅

**Comment by nelsonic** [comment]
@iteles given that I have a simple design and workflow for building these shelves, I could easily cover the remaining 3 walls with more storage by the end of the week if you feel this is a priority. ⏳

**Comment by nelsonic** [comment]
Just say the word and I will get to work on the next set of shelves. Until then I’m getting back to my desk work. 👌
